from typing import List, Optional

from tut_bot.models.schemas import Exercise

EXERCISES_DATABASE: List[Exercise] = [
    # =========================================================================
    # ALEMÁN (de-DE)
    # =========================================================================
    # 1. Ich-Laut (/ç/) vs Ach-Laut (/x/)
    Exercise(
        id="de-phon-01",
        language="de-DE",
        category="ich-Laut vs ach-Laut",
        level="A1",
        title="El sonido de 'Ich' (Ich-Laut /ç/)",
        target_text="Ich spreche kein Deutsch.",
        ipa="ɪç ˈʃpʁɛçə kaɪn dɔɪtʃ",
        phonetic_guide="Ij shpreje kain doitch",
        phonetic_notes="ç = ch suave palatal (como siseo), ʃ = sonido sh inglesa",
        translation_es="No hablo alemán.",
        focus_phonemes=["ç", "ʃ"],
        tip="El sonido de 'ch' tras 'i/e' (/ç/) es palatal, como un siseo suave con la lengua pegada al paladar medio, nunca una 'k' ni una 'j' áspera española.",
        articulation_type="palatal",
    ),
    Exercise(
        id="de-phon-02",
        language="de-DE",
        category="ich-Laut vs ach-Laut",
        level="A1",
        title="El sonido de 'Buch' (Ach-Laut /x/)",
        target_text="Das Buch liegt auf dem Tisch.",
        ipa="das buːx liːkt aʊf deːm tɪʃ",
        phonetic_guide="Das buj liikt auf deem tish",
        phonetic_notes="x = ch velar (como jota española suave tras a/o/u), ʃ = sh",
        translation_es="El libro está sobre la mesa.",
        focus_phonemes=["x", "ʃ"],
        tip="Tras vocales posteriores (a, o, u), la 'ch' se pronuncia en la parte posterior (velar /x/), similar a la 'j' española suave.",
        articulation_type="velar",
    ),
    Exercise(
        id="de-phon-03",
        language="de-DE",
        category="ich-Laut vs ach-Laut",
        level="A2",
        title="Contraste directo Ich vs Ach",
        target_text="Ich suche ein einfaches Buch.",
        ipa="ɪç ˈzuːxə aɪn ˈaɪnfaχəs buːx",
        phonetic_guide="Ij zuuje ain áinfajes buuj",
        phonetic_notes="ç suave en 'Ich', x profunda en 'suche' y 'Buch'",
        translation_es="Busco un libro sencillo.",
        focus_phonemes=["ç", "x"],
        tip="Observa cómo cambia de /ç/ en 'Ich' a /x/ en 'suche' y 'Buch'.",
        articulation_type="palatal",
    ),
    Exercise(
        id="de-phon-04",
        language="de-DE",
        category="ich-Laut vs ach-Laut",
        level="B1",
        title="Tríada Fricativa: /ç/ vs /x/ vs /ʃ/",
        target_text="Ich möchte sechs frische Fische kochen.",
        ipa="ɪç ˈmœçtə zɛks ˈfʁɪʃə ˈfɪʃə ˈkɔxn̩",
        phonetic_guide="Ij méj-te zeks frishe fishe kojen",
        phonetic_notes="ö = boca en 'o' diciendo 'e', sechs = zeks con ks",
        translation_es="Quisiera cocinar seis pescados frescos.",
        focus_phonemes=["ç", "ʃ", "x"],
        tip="Diferencia con precisión: /ç/ en 'Ich/möchte', /ks/ en 'sechs', /ʃ/ en 'frische/Fische' y /x/ en 'kochen'.",
        articulation_type="palatal",
    ),
    # 2. Vocales con diéresis (Umlauts: ä, ö, ü)
    Exercise(
        id="de-umlaut-01",
        language="de-DE",
        category="Umlauts (ä, ö, ü)",
        level="A1",
        title="Umlaut Ö (/øː/, /œ/)",
        target_text="Ich möchte ein Brötchen möchten.",
        ipa="ɪç ˈmœçtə aɪn ˈbʁøːtçən",
        phonetic_guide="Ij méj-te ain bréet-jien méj-ten",
        phonetic_notes="ö (/øː/, /œ/) = labios redondeados en 'o' pronunciando 'e'",
        translation_es="Quisiera un panecillo.",
        focus_phonemes=["øː", "œ", "ç"],
        tip="Para pronunciar 'ö', coloca la boca en posición de decir 'o' (labios redondeados), pero intenta emitir una 'e'. ¡No abras los labios!",
        articulation_type="vowel",
    ),
    Exercise(
        id="de-umlaut-02",
        language="de-DE",
        category="Umlauts (ä, ö, ü)",
        level="A1",
        title="Umlaut Ü (/yː/, /ʏ/)",
        target_text="Für fünf Schüler gibt es Übungen.",
        ipa="fyːɐ̯ fʏnf ˈʃyːlɐ ɡɪpt ɛs ˈyːbʊŋən",
        phonetic_guide="Fiur fiunf shiuler gipt es iubunguen",
        phonetic_notes="ü (/yː/, /ʏ/) = labios en beso de 'u' pronunciando 'i'",
        translation_es="Para cinco alumnos hay ejercicios.",
        focus_phonemes=["yː", "ʏ"],
        tip="Para 'ü', pon los labios como si fueras a dar un beso (posición de 'u'), pero pronuncia 'i'.",
        articulation_type="vowel",
    ),
    Exercise(
        id="de-umlaut-03",
        language="de-DE",
        category="Umlauts (ä, ö, ü)",
        level="A2",
        title="Umlaut Ä (/ɛː/)",
        target_text="Die Mädchen wählen schöne Äpfel.",
        ipa="diː ˈmɛːtçən ˈvɛːlən ˈʃøːnə ˈɛpfəl",
        phonetic_guide="Dii méet-jien véelen shéene épfel",
        phonetic_notes="ä (/ɛː/) = 'e' abierta bajando la mandíbula; ö = 'e' con labios en 'o'",
        translation_es="Las chicas eligen manzanas hermosas.",
        focus_phonemes=["ɛː", "ç", "øː"],
        tip="La 'ä' es una 'e' abierta. Baja ligeramente la mandíbula inferior manteniendo la lengua adelante.",
        articulation_type="vowel",
    ),
    Exercise(
        id="de-umlaut-04",
        language="de-DE",
        category="Umlauts (ä, ö, ü)",
        level="A2",
        title="Contraste O base vs. Ö Umlaut",
        target_text="Ist es schon spät für dieses schöne Konzert?",
        ipa="ɪst ɛs ʃoːn ʃpɛːt fyːɐ̯ ˈdiːzəs ˈʃøːnə kɔnˈtsɛʁt",
        phonetic_guide="Ist es shoon shpéet fiur diizes shéene kontsert?",
        phonetic_notes="schon (o pura) vs schöne (ö redondeada), z = ts en Konzert",
        translation_es="¿Ya es tarde para este hermoso concierto?",
        focus_phonemes=["oː", "øː", "ʃ", "ts"],
        tip="Compara 'schon' (/oː/ posterior) con 'schöne' (/øː/ anterior redondeada con labios en óvalo cerrado).",
        articulation_type="vowel",
    ),
    # 3. Pares Mínimos Vocálicos Alemanes (Vocal Larga Tensa vs Corta Relajada)
    Exercise(
        id="de-vowel-len-01",
        language="de-DE",
        category="Pares Mínimos Vocálicos",
        level="A2",
        title="Larga /iː/ vs Corta /ɪ/ (bieten vs bitten)",
        target_text="Wir bieten Hilfe, wenn Sie höflich bitten.",
        ipa="viːɐ̯ ˈbiːtn̩ ˈhɪlfə vɛn ziː ˈhøːflɪç ˈbɪtn̩",
        phonetic_guide="Viir biiten jilfe, ven zii jéeflij biten",
        phonetic_notes="bieten (ii larga) vs bitten (i corta seca)",
        translation_es="Ofrecemos ayuda si usted pide cortésmente.",
        focus_phonemes=["iː", "ɪ", "øː", "ç"],
        tip="En 'bieten' la 'ie' es larga, tensa y sonriente (/iː/). En 'bitten' la 'i' es corta y relajada (/ɪ/).",
        articulation_type="vowel",
    ),
    Exercise(
        id="de-vowel-len-02",
        language="de-DE",
        category="Pares Mínimos Vocálicos",
        level="A2",
        title="Larga /eː/ vs Corta /ɛ/ (Beet vs Bett)",
        target_text="Die Blumen im Beet und das weiche Bett.",
        ipa="diː ˈbluːmən ɪm beːt ʊnt das ˈvaɪçə bɛt",
        phonetic_guide="Dii bluumen im beet unt das vaíje bet",
        phonetic_notes="Beet (ee larga) vs Bett (e corta y seca)",
        translation_es="Las flores en el parterre y la cama blanda.",
        focus_phonemes=["eː", "ɛ", "ç", "t"],
        tip="'Beet' tiene una /eː/ larga y cerrada; 'Bett' tiene una /ɛ/ corta, abierta y seca.",
        articulation_type="vowel",
    ),
    Exercise(
        id="de-vowel-len-03",
        language="de-DE",
        category="Pares Mínimos Vocálicos",
        level="A2",
        title="Larga /yː/ vs Corta /ʏ/ (fühlen vs füllen)",
        target_text="Wir fühlen die Kälte und füllen die Gläser.",
        ipa="viːɐ̯ ˈfyːlən diː ˈkɛltə ʊnt ˈfʏlən diː ˈɡlɛːzɐ",
        phonetic_guide="Viir fiulen dii kélte unt fiulen dii gléezer",
        phonetic_notes="fühlen (ü sostenida larga) vs füllen (ü corta rápida)",
        translation_es="Sentimos el frío y llenamos los vasos.",
        focus_phonemes=["yː", "ʏ", "ɛː"],
        tip="'fühlen' tiene una 'ü' larga y tensa (/yː/). En 'füllen' la doble 'll' acorta la vocal a /ʏ/ relajada.",
        articulation_type="vowel",
    ),
    # 4. Sibilantes y Fricativas Alemanas (/s/ sorda vs /z/ sonora vs /ts/)
    Exercise(
        id="de-s-z-01",
        language="de-DE",
        category="Sibilantes y Fricativas",
        level="B1",
        title="Sonora /z/ vs Sorda /s/ (reisen vs reißen)",
        target_text="Sie reisen gern und reißen alte Zettel ab.",
        ipa="ziː ˈʁaɪzn̩ ɡɛʁn ʊnt ˈʁaɪsn̩ ˈaltə ˈtsɛtl̩ ap",
        phonetic_guide="Zii ráizen guern unt ráisen álte tsétel ap",
        phonetic_notes="reisen (s vibrada como abeja) vs reißen (s sorda normal), Zettel = ts",
        translation_es="Ellos viajan con gusto y rompen notas viejas.",
        focus_phonemes=["z", "s", "ts"],
        tip="'reisen' tiene 's' intervocálica sonora (/z/, con vibración laríngea como abeja). 'reißen' (ß) es totalmente sorda (/s/).",
        articulation_type="alveolar",
    ),
    # 5. Auslautverhärtung (Ensordecimiento final de consonantes)
    Exercise(
        id="de-auslaut-01",
        language="de-DE",
        category="Auslautverhärtung (Finales)",
        level="A2",
        title="Consonantes finales duras (d->t, b->p, g->k)",
        target_text="Guten Tag, das ist ein schönes Bild!",
        ipa="ˈɡuːtn taːk das ɪst aɪn ˈʃøːnəs bɪlt",
        phonetic_guide="Guuten taak, das ist ain shéenes bilt!",
        phonetic_notes="Tag termina en sonido /k/, Bild termina en sonido /t/",
        translation_es="¡Buen día, esta es una hermosa imagen!",
        focus_phonemes=["k", "t", "p"],
        tip="Al final de palabra o sílaba en alemán, 'Tag' termina en sonido sordo /k/, y 'Bild' termina en sonido /t/ sin vibrar.",
        articulation_type="alveolar",
    ),
    # 6. R Alemana (Uvular /ʁ/ vs Vocalizada /ɐ/)
    Exercise(
        id="de-r-01",
        language="de-DE",
        category="La 'R' Alemana",
        level="A2",
        title="R uvular inicial vs R vocalizada final",
        target_text="Der Lehrer trinkt klares Wasser.",
        ipa="deːɐ̯ ˈleːʁɐ tʁɪŋkt ˈklaːʁəs ˈvasɐ",
        phonetic_guide="Dee-a lee-ra tringt klaares vasa",
        phonetic_notes="ʁ = r uvular campanilla, ɐ = r final suena como 'a' relajada",
        translation_es="El profesor bebe agua clara.",
        focus_phonemes=["ʁ", "ɐ"],
        tip="Al final de palabra (-er, der), la 'r' se vocaliza en /ɐ/ (suena como una 'a' corta y relajada). Al inicio, vibra suavemente en la campanilla.",
        articulation_type="uvular",
    ),
    # 7. Zungenbrecher (Trabalenguas)
    Exercise(
        id="de-tongue-twister-01",
        language="de-DE",
        category="Zungenbrecher (Trabalenguas)",
        level="B1",
        title="Zungenbrecher de 'Fischers Fritz'",
        target_text="Fischers Fritz fischt frische Fische.",
        ipa="ˈfɪʃɐs fʁɪts fɪʃt ˈfʁɪʃə ˈfɪʃə",
        phonetic_guide="Fisherz frits fisht frishe fishe",
        phonetic_notes="ʃ = sonido sh, ts = ts en Fritz",
        translation_es="Fritz el pescador pesca peces frescos.",
        focus_phonemes=["ʃ", "ts", "ʁ", "ɪ"],
        tip="Combina con agilidad la fricativa postalveolar /ʃ/ con la africada /ts/ y la R uvular /ʁ/.",
        articulation_type="postalveolar",
    ),
    # 8. Vida Cotidiana A1-B1
    Exercise(
        id="de-daily-01",
        language="de-DE",
        category="Vida Cotidiana",
        level="A1",
        title="Pedir en una cafetería",
        target_text="Entschuldigung, kann ich bitte einen Kaffee haben?",
        ipa="ɛntˈʃʊldɪɡʊŋ kan ɪç ˈbɪtə ˈaɪnən ˈkafeː ˈhaːbn̩",
        phonetic_guide="Ent-shúldigung, kan ij bite áinen kafee jaaben?",
        phonetic_notes="ʃ = sh en Entschuldigung, ç = ch suave en ich",
        translation_es="Disculpe, ¿puedo pedir un café por favor?",
        focus_phonemes=["ç", "ʃ"],
        tip="Presta atención a la fluidez y a la unión de palabras en preguntas de cortesía.",
        articulation_type="palatal",
    ),
    Exercise(
        id="de-daily-02",
        language="de-DE",
        category="Vida Cotidiana",
        level="B1",
        title="Expresar opinión con oraciones subordinadas",
        target_text="Ich glaube, dass wir heute noch pünktlich ankommen.",
        ipa="ɪç ˈɡlaʊbə das viːɐ̯ ˈhɔɪtə nɔx ˈpʏŋktlɪç ˈankɔmən",
        phonetic_guide="Ij gláube, das viir jóite noj piúnktlij ánkomen",
        phonetic_notes="ç suave en ich/pünktlich, x en noch, ü en pünktlich",
        translation_es="Creo que hoy todavía llegaremos puntuales.",
        focus_phonemes=["ç", "x", "ʏ"],
        tip="Cuida la entonación que desciende al final de la cláusula subordinada y la pronunciación de 'pünktlich'.",
        articulation_type="palatal",
    ),
    # =========================================================================
    # INGLÉS (en-US)
    # =========================================================================
    # 1. Sonidos TH (/θ/ sordo vs /ð/ sonoro)
    Exercise(
        id="en-th-01",
        language="en-US",
        category="TH Sounds (/θ/ vs /ð/)",
        level="A1",
        title="Unvoiced TH (/θ/ como en 'think')",
        target_text="I think thirty three things are thrilling.",
        ipa="aɪ θɪŋk ˈθɜːti θriː θɪŋz ɑːr ˈθrɪlɪŋ",
        phonetic_guide="Ai zink zer-ti zrii zings ar zriling",
        phonetic_notes="θ = th sorda (como la 'z' española peninsular en zapato, sin vibrar)",
        translation_es="Creo que treinta y tres cosas son emocionantes.",
        focus_phonemes=["θ"],
        tip="Coloca la punta de la lengua suavemente entre los dientes frontales e impulsa aire sin vibrar las cuerdas vocales.",
        articulation_type="dental",
    ),
    Exercise(
        id="en-th-02",
        language="en-US",
        category="TH Sounds (/θ/ vs /ð/)",
        level="A1",
        title="Voiced TH (/ð/ como en 'this')",
        target_text="This is their father and mother.",
        ipa="ðɪs ɪz ðɛr ˈfɑːðər ænd ˈmʌðər",
        phonetic_guide="Dhis iz dher faa-dher end ma-dher",
        phonetic_notes="ð = th sonora (lengua entre dientes con vibración, como una d suave)",
        translation_es="Este es el padre y la madre de ellos.",
        focus_phonemes=["ð"],
        tip="Misma posición interdental de la lengua, pero haciendo vibrar activamente la garganta (cuerdas vocales).",
        articulation_type="dental",
    ),
    Exercise(
        id="en-th-03",
        language="en-US",
        category="TH Sounds (/θ/ vs /ð/)",
        level="A2",
        title="Contraste directo: Breath (/θ/) vs. Breathe (/ð/)",
        target_text="Take a deep breath and breathe calmly.",
        ipa="teɪk ə diːp brɛθ ænd briːð ˈkɑːmli",
        phonetic_guide="Teik e diip brez end briidh kaam-li",
        phonetic_notes="breath (termina en z sorda) vs breathe (termina en d suave vibrada)",
        translation_es="Toma una respiración profunda y respira con calma.",
        focus_phonemes=["θ", "ð", "iː", "ɛ"],
        tip="'Breath' termina en /θ/ sorda; 'breathe' tiene vocal larga /iː/ y termina en /ð/ sonora con vibración.",
        articulation_type="dental",
    ),
    # 2. Pares Mínimos Vocálicos (Interferencia común del español)
    Exercise(
        id="en-vowels-01",
        language="en-US",
        category="Pares Mínimos Vocálicos",
        level="A2",
        title="Sheep /iː/ vs Ship /ɪ/",
        target_text="The big sheep sleeps on the green hill.",
        ipa="ðə bɪɡ ʃiːp sliːps ɑːn ðə ɡriːn hɪl",
        phonetic_guide="Dhe big shiip sliips on dhe griin jil",
        phonetic_notes="iː = i larga tensa (sheep/sleeps), ɪ = i corta relajada (big/hill)",
        translation_es="La gran oveja duerme sobre la colina verde.",
        focus_phonemes=["iː", "ɪ"],
        tip="En 'sleeps' la vocal es tensa y sonriente (/iː/). En 'big' e 'hill', la vocal es relajada, corta y central (/ɪ/).",
        articulation_type="vowel",
    ),
    Exercise(
        id="en-vowels-02",
        language="en-US",
        category="Pares Mínimos Vocálicos",
        level="A2",
        title="Cat /æ/ vs Cut /ʌ/",
        target_text="The black cat jumped over the cup.",
        ipa="ðə blæk kæt dʒʌmpt ˈoʊvər ðə kʌp",
        phonetic_guide="Dhe blek ket dyompt ou-ver dhe cop",
        phonetic_notes="æ = a abierta (entre a y e en cat), ʌ = u corta central (cup)",
        translation_es="El gato negro saltó sobre la taza.",
        focus_phonemes=["æ", "ʌ"],
        tip="/æ/ requiere abrir la mandíbula hacia abajo como diciendo 'a' con lengua de 'e'. /ʌ/ es neutra y breve en el centro.",
        articulation_type="vowel",
    ),
    Exercise(
        id="en-vowels-03",
        language="en-US",
        category="Pares Mínimos Vocálicos",
        level="A2",
        title="Pull /ʊ/ vs. Pool /uː/",
        target_text="Please pull the rope before you jump in the pool.",
        ipa="pliːz pʊl ðə roʊp bɪˈfɔːr juː dʒʌmp ɪn ðə puːl",
        phonetic_guide="Pliiz pul dhe roup bi-for yu dyamp in dhe puul",
        phonetic_notes="pull (ʊ corta relajada) vs pool (uu larga redonda)",
        translation_es="Por favor jala la cuerda antes de saltar a la piscina.",
        focus_phonemes=["ʊ", "uː"],
        tip="'Pull' usa /ʊ/ corta y relajada (labios semi-redondeados). 'Pool' usa /uː/ tensa, larga y con labios en círculo cerrado.",
        articulation_type="vowel",
    ),
    Exercise(
        id="en-vowels-04",
        language="en-US",
        category="Pares Mínimos Vocálicos",
        level="B1",
        title="Cot /ɑː/ vs. Caught /ɔː/ vs. Coat /oʊ/",
        target_text="Paul caught a cold and put on his warm coat.",
        ipa="pɔːl kɑːt ə koʊld ænd pʊt ɑːn hɪz wɔːrm koʊt",
        phonetic_guide="Pool coot e could end put on jiz vorm cout",
        phonetic_notes="caught (ɔː abierta) vs coat (oʊ diptongo ou)",
        translation_es="Paul se resfrió y se puso su abrigo cálido.",
        focus_phonemes=["ɔː", "oʊ", "ɑː"],
        tip="No sustituyas todas por la 'o' española: /ɔː/ es abierta y posterior, mientras que /oʊ/ en 'coat' es un diptongo dinámico.",
        articulation_type="vowel",
    ),
    # 3. Labiodental V (/v/) vs Bilabial B (/b/)
    Exercise(
        id="en-b-v-01",
        language="en-US",
        category="V vs B",
        level="A1",
        title="Distinguiendo V (/v/) de B (/b/)",
        target_text="Very best friends travel by van and boat.",
        ipa="ˈvɛri bɛst frɛndz ˈtrævəl baɪ væn ænd boʊt",
        phonetic_guide="Véri best frendz trável bai van end bout",
        phonetic_notes="v = dientes superiores rozando labio inferior con vibración, no b",
        translation_es="Los mejores amigos viajan en furgoneta y barco.",
        focus_phonemes=["v", "b"],
        tip="En español no diferenciamos B de V. En inglés, para la 'V' tus dientes superiores DEBEN tocar el labio inferior con fricción acústica continua.",
        articulation_type="labiodental",
    ),
    # 4. Semivocal W (/w/) vs Labiodental V (/v/)
    Exercise(
        id="en-w-v-01",
        language="en-US",
        category="W vs V",
        level="A2",
        title="West (/w/) vs. Vest (/v/)",
        target_text="We went west wearing very warm vests.",
        ipa="wiː wɛnt wɛst ˈwɛrɪŋ ˈvɛri wɔːrm vɛsts",
        phonetic_guide="Uii uent uest uéring véri uorm vests",
        phonetic_notes="w = labios en u redonda sin tocar dientes vs v = dientes en labio",
        translation_es="Fuimos al oeste vistiendo chalecos muy abrigados.",
        focus_phonemes=["w", "v"],
        tip="Para 'W' (/w/), los dientes NUNCA tocan los labios (redondea como una 'u'). Para 'V' (/v/), los dientes superiores rozan el labio inferior.",
        articulation_type="labiodental",
    ),
    # 5. Líquidas y Aproximantes (R rótica /ɹ/ vs L lateral /l/)
    Exercise(
        id="en-r-l-01",
        language="en-US",
        category="Líquidas (R vs L)",
        level="A2",
        title="American R (/ɹ/) vs. L (/l/)",
        target_text="The red light turns right along the long river.",
        ipa="ðə rɛd laɪt tɜːrnz raɪt əˈlɔːŋ ðə lɔːŋ ˈrɪvər",
        phonetic_guide="Dhe red lait ternz rait e-long dhe long ri-ver",
        phonetic_notes="r americana = lengua curvada hacia atrás sin tocar paladar",
        translation_es="La luz roja gira a la derecha a lo largo del río largo.",
        focus_phonemes=["r", "l"],
        tip="Para la 'R' en inglés americano (/ɹ/), la lengua se curva hacia atrás sin tocar el paladar ni vibrar. Para la 'L' (/l/), la punta toca firmemente detrás de los dientes.",
        articulation_type="alveolar",
    ),
    # 6. Terminaciones Morfológicas Gramaticales (-ed endings: /t/, /d/, /ɪd/)
    Exercise(
        id="en-endings-ed-01",
        language="en-US",
        category="Terminaciones Gramaticales (-ed)",
        level="B1",
        title="Pasado Regular -ed: /t/, /d/ e /ɪd/",
        target_text="She walked to the park, played music, and waited.",
        ipa="ʃiː wɔːkt tuː ðə pɑːrk pleɪd ˈmjuːzɪk ænd ˈweɪtɪd",
        phonetic_guide="Shii uokt tu dhe park, pleid miúzik, end uéitid",
        phonetic_notes="walked (/t/), played (/d/), waited (/ɪd/)",
        translation_es="Ella caminó al parque, tocó música y esperó.",
        focus_phonemes=["t", "d", "ɪd"],
        tip="'walked' termina en sonido seco /t/; 'played' termina en sonido sonoro /d/; solo 'waited' (tras sonido t/d) añade una sílaba extra /ɪd/.",
        articulation_type="alveolar",
    ),
    # 7. Tongue Twisters (Trabalenguas en Inglés)
    Exercise(
        id="en-tongue-twister-01",
        language="en-US",
        category="Tongue Twisters (Trabalenguas)",
        level="B1",
        title="She sells seashells (/s/ vs /ʃ/)",
        target_text="She sells seashells by the seashore.",
        ipa="ʃiː sɛlz ˈsiːʃɛlz baɪ ðə ˈsiːʃɔːr",
        phonetic_guide="Shii selz sii-shelz bai dhe sii-shor",
        phonetic_notes="s = s dental normal vs ʃ = sonido sh",
        translation_es="Ella vende conchas marinas a la orilla del mar.",
        focus_phonemes=["ʃ", "s", "z"],
        tip="Entrena la transición veloz entre la sibilante alveolar /s/ en 'sells/sea' y la postalveolar /ʃ/ en 'she/shells/shore'.",
        articulation_type="postalveolar",
    ),
    # 8. Conversación Cotidiana
    Exercise(
        id="en-daily-01",
        language="en-US",
        category="Conversación Cotidiana",
        level="B1",
        title="Presentación profesional y proyectos",
        target_text="I would really appreciate your feedback on this project.",
        ipa="aɪ wʊd ˈrɪəli əˈpriːʃieɪt jʊər ˈfiːdbæk ɑːn ðɪs ˈprɑːdʒɛkt",
        phonetic_guide="Ai uud ríi-li e-príi-shieit yor fíid-bek on dhis pródyeckt",
        phonetic_notes="ʃ = sh en appreciate, ð = th en this, æ = a en feedback",
        translation_es="Realmente agradecería tus comentarios sobre este proyecto.",
        focus_phonemes=["ʃ", "ð", "æ"],
        tip="Enfócate en la fluidez del ritmo y la reducción de sonidos no acentuados ('would', 'your').",
        articulation_type="postalveolar",
    ),
    # =========================================================================
    # ALEMÁN - ESCRITURA (Schreiben) A1, A2, B1
    # =========================================================================
    Exercise(
        id="de-write-01",
        language="de-DE",
        category="Oraciones Básicas y Presentación",
        level="A1",
        skill_type="writing",
        title="Presentación y Lugar de Residencia",
        prompt="✍️ Escribe en alemán: 'Hola, me llamo Carlos y vivo en Berlín.'",
        target_text="Hallo, ich heiße Carlos und ich wohne in Berlin.",
        translation_es="Hola, me llamo Carlos y vivo en Berlín.",
        tip="Recuerda conjugar los verbos en primera persona: 'ich heiße' y 'ich wohne'.",
        vocabulary_breakdown={
            "heißen": "llamarse (ich heiße, du heißt)",
            "wohnen": "vivir / residir (ich wohne)",
            "und": "y (conjunción)",
            "in": "en (preposición de lugar)",
        },
        grammar_note="En alemán los nombres propios y las ciudades se escriben con mayúscula inicial.",
    ),
    Exercise(
        id="de-write-02",
        language="de-DE",
        category="Artículos y Acusativo",
        level="A1",
        skill_type="writing",
        title="Mascotas y Objeto Directo (Akkusativ)",
        prompt="✍️ Traduce al alemán: 'Tengo un perro y una gata.' (Ojo con el artículo de perro: der Hund)",
        target_text="Ich habe einen Hund und eine Katze.",
        translation_es="Tengo un perro y una gata.",
        tip="El verbo 'haben' rige Acusativo. El masculino 'der Hund' se convierte en 'einen Hund', mientras el femenino 'eine Katze' se mantiene.",
        vocabulary_breakdown={
            "haben": "tener (ich habe)",
            "der Hund": "el perro ➔ acusativo: einen Hund",
            "die Katze": "la gata / gato hembra ➔ acusativo: eine Katze",
        },
        grammar_note="En alemán TODOS los sustantivos (Hund, Katze, etc.) se escriben con mayúscula inicial obligatoria.",
    ),
    Exercise(
        id="de-write-03",
        language="de-DE",
        category="Pasado Perfekt",
        level="A2",
        skill_type="writing",
        title="Acciones Pasadas Cotidianas",
        prompt="✍️ Escribe en pasado (Perfekt): 'Ayer compré un café.'",
        target_text="Gestern habe ich einen Kaffee gekauft.",
        translation_es="Ayer compré un café.",
        tip="Estructura del Perfekt: Verbo auxiliar (habe) en posición 2 y participio (gekauft) al final de la oración.",
        vocabulary_breakdown={
            "gestern": "ayer",
            "kaufen": "comprar (participio: gekauft)",
            "der Kaffee": "el café ➔ acusativo: einen Kaffee",
        },
        grammar_note="Si la oración comienza con un adverbio de tiempo como 'Gestern', el sujeto y el verbo se invierten (inversión sujeto-verbo).",
    ),
    Exercise(
        id="de-write-04",
        language="de-DE",
        category="Oraciones Subordinadas (weil)",
        level="A2",
        skill_type="writing",
        title="Dar Razones con 'weil'",
        prompt="✍️ Une con 'weil' (porque): 'Aprendo alemán porque es interesante.'",
        target_text="Ich lerne Deutsch, weil es interessant ist.",
        translation_es="Aprendo alemán porque es interesante.",
        tip="La conjunción subordinante 'weil' envía el verbo conjugado ('ist') al final absoluto de la cláusula.",
        vocabulary_breakdown={
            "lernen": "aprender",
            "weil": "porque (conjunción que altera el orden)",
            "interessant": "interesante",
            "ist": "es / está (verbo sein)",
        },
        grammar_note="Regla de oro: Antes de 'weil' siempre se escribe una coma (, weil ... verb final).",
    ),
    Exercise(
        id="de-write-05",
        language="de-DE",
        category="Cortesía y Negocios (B1)",
        level="B1",
        skill_type="writing",
        title="Solicitud Formal de Cita",
        prompt="✍️ Escribe con cortesía formal: 'Me gustaría acordar una cita, por favor.'",
        target_text="Ich möchte bitte einen Termin vereinbaren.",
        translation_es="Me gustaría acordar una cita, por favor.",
        tip="Usa 'möchte' + infinitivo al final ('vereinbaren'). 'Der Termin' pasa a 'einen Termin' en acusativo.",
        vocabulary_breakdown={
            "möchte": "me gustaría (forma de cortesía)",
            "der Termin": "la cita profesional o médica",
            "vereinbaren": "pactar / agendar",
            "bitte": "por favor",
        },
        grammar_note="Los verbos modales colocan el segundo verbo en infinitivo al final de la frase.",
    ),
    # =========================================================================
    # ALEMÁN - COMPRENSIÓN AUDITIVA (Hören) A1, A2
    # =========================================================================
    Exercise(
        id="de-listen-01",
        language="de-DE",
        category="Horarios y Números (Hören)",
        level="A1",
        skill_type="listening",
        title="¿A qué hora es la reunión?",
        prompt="👂 Escucha el audio nativo y selecciona la hora exacta que se indica:",
        target_text="Das Treffen beginnt um Viertel vor acht.",
        translation_es="La reunión comienza a las ocho menos cuarto (7:45).",
        tip="Presta atención a 'Viertel vor' (un cuarto antes de...) vs 'Viertel nach'.",
        options=[
            "7:45 (Viertel vor acht)",
            "8:15 (Viertel nach acht)",
            "8:45 (Viertel vor neun)",
        ],
        correct_option_index=0,
        vocabulary_breakdown={
            "das Treffen": "la reunión / encuentro",
            "beginnt": "comienza (beginnen)",
            "Viertel": "cuarto de hora (15 minutos)",
            "vor": "antes de (menos)",
        },
        grammar_note="Para las horas en alemán informal: 'Viertel vor' resta 15 minutos a la hora siguiente.",
    ),
    Exercise(
        id="de-listen-02",
        language="de-DE",
        category="Profesiones y Lugares (Hören)",
        level="A1",
        skill_type="listening",
        title="¿En qué trabaja Maria?",
        prompt="👂 Escucha el audio y elige a qué se dedica Maria:",
        target_text="Maria arbeitet als Ärztin in einem großen Krankenhaus.",
        translation_es="Maria trabaja como médica en un hospital grande.",
        tip="Escucha la palabra compuesta 'Krankenhaus' y la profesión 'Ärztin'.",
        options=[
            "Es profesora en una universidad",
            "Es médica en un hospital",
            "Es abogada en una oficina",
        ],
        correct_option_index=1,
        vocabulary_breakdown={
            "arbeiten als": "trabajar como (profesión)",
            "die Ärztin": "la médica",
            "das Krankenhaus": "el hospital (Kranken = enfermos + Haus = casa)",
            "groß": "grande",
        },
    ),
    # =========================================================================
    # INGLÉS - ESCRITURA (Writing) A1, A2, B1
    # =========================================================================
    Exercise(
        id="en-write-01",
        language="en-US",
        category="Present Simple y Rutinas",
        level="A1",
        skill_type="writing",
        title="Tercera Persona en Presente",
        prompt="✍️ Escribe en inglés: 'Ella trabaja en un banco y vive cerca de aquí.'",
        target_text="She works in a bank and lives near here.",
        translation_es="Ella trabaja en un banco y vive cerca de aquí.",
        tip="En presente simple con he/she/it, no olvides añadir la '-s' final a los verbos: 'works' y 'lives'.",
        vocabulary_breakdown={
            "works": "trabaja (work + s)",
            "lives": "vive (live + s)",
            "bank": "banco",
            "near here": "cerca de aquí",
        },
        grammar_note="La tercera persona del singular en inglés requiere -s o -es en afirmativo.",
    ),
    Exercise(
        id="en-write-02",
        language="en-US",
        category="Past Simple Irregular",
        level="A2",
        skill_type="writing",
        title="Objetos Perdidos en Pasado",
        prompt="✍️ Traduce al inglés en pasado simple: 'Ayer encontré mis llaves debajo de la cama.'",
        target_text="Yesterday I found my keys under the bed.",
        translation_es="Ayer encontré mis llaves debajo de la cama.",
        tip="'find' es un verbo irregular: su pasado simple es 'found', no 'finded'.",
        vocabulary_breakdown={
            "found": "encontré (pasado de find)",
            "keys": "llaves",
            "under": "debajo de",
            "bed": "cama",
        },
        grammar_note="Los verbos irregulares en inglés cambian su raíz en pasado simple.",
    ),
    Exercise(
        id="en-write-03",
        language="en-US",
        category="Present Perfect vs Past Simple",
        level="B1",
        skill_type="writing",
        title="Experiencia y Duración en el Tiempo",
        prompt="✍️ Traduce usando Present Perfect: 'He vivido en esta ciudad durante tres años.'",
        target_text="I have lived in this city for three years.",
        translation_es="He vivido en esta ciudad durante tres años.",
        tip="Usa 'for' para indicar duración ('for three years') y 'since' para un punto de inicio específico.",
        vocabulary_breakdown={
            "have lived": "he vivido (present perfect)",
            "for": "durante (periodo de tiempo acumulado)",
            "since": "desde (año o fecha específica)",
            "city": "ciudad",
        },
        grammar_note="El Present Perfect conecta una acción que empezó en el pasado y continúa en el presente.",
    ),
    # =========================================================================
    # INGLÉS - COMPRENSIÓN AUDITIVA (Listening) A1, A2
    # =========================================================================
    Exercise(
        id="en-listen-01",
        language="en-US",
        category="Situaciones Cotidianas (Listening)",
        level="A1",
        skill_type="listening",
        title="Aviso en el Aeropuerto",
        prompt="👂 Escucha el anuncio de voz y responde: ¿Por qué se canceló el vuelo?",
        target_text="Attention passengers, flight 402 is cancelled due to heavy rain.",
        translation_es="Atención pasajeros, el vuelo 402 está cancelado debido a lluvia intensa.",
        tip="Identifica la expresión 'due to' (debido a) y la condición climática.",
        options=[
            "Por lluvia intensa (heavy rain)",
            "Por fallas mecánicas en el avión",
            "Por huelga del personal del aeropuerto",
        ],
        correct_option_index=0,
        vocabulary_breakdown={
            "due to": "debido a / a causa de",
            "cancelled": "cancelado",
            "heavy rain": "lluvia intensa",
            "flight": "vuelo",
        },
    ),
]


def get_exercises(
    language: Optional[str] = None,
    category: Optional[str] = None,
    level: Optional[str] = None,
    skill_type: Optional[str] = None,
) -> List[Exercise]:
    results = EXERCISES_DATABASE
    if language:
        results = [e for e in results if e.language.lower() == language.lower()]
    if category:
        results = [e for e in results if e.category.lower() == category.lower()]
    if level:
        results = [e for e in results if e.level.lower() == level.lower()]
    if skill_type:
        target_skill = (
            "listening"
            if skill_type.lower() in ("listening", "comprehension")
            else skill_type.lower()
        )
        results = [e for e in results if (e.skill_type or "speaking").lower() == target_skill]
    return results


def get_categories(language: str) -> List[str]:
    seen = set()
    categories = []
    for e in EXERCISES_DATABASE:
        if e.language.lower() == language.lower() and e.category not in seen:
            seen.add(e.category)
            categories.append(e.category)
    return categories
