from typing import List, Optional

from tut_bot.models.schemas import Exercise

EXERCISES_DATABASE: List[Exercise] = [
    # =========================================================================
    # ALEMÁN (de-DE)
    # =========================================================================
    # 1. Ich-Laut (/ç/) vs Ach-Laut (/x/)
    Exercise(
        id="de-phon-01",
        language="de-DE",
        category="ich-Laut vs ach-Laut",
        level="A1",
        title="El sonido de 'Ich' (Ich-Laut /ç/)",
        target_text="Ich spreche kein Deutsch.",
        ipa="ɪç ˈʃpʁɛçə kaɪn dɔɪtʃ",
        phonetic_guide="Ij shpreje kain doitch",
        phonetic_notes="ç = ch suave palatal (como siseo), ʃ = sonido sh inglesa",
        translation_es="No hablo alemán.",
        focus_phonemes=["ç", "ʃ"],
        tip="El sonido de 'ch' tras 'i/e' (/ç/) es palatal, como un siseo suave con la lengua pegada al paladar medio, nunca una 'k' ni una 'j' áspera española.",
        articulation_type="palatal",
    ),
    Exercise(
        id="de-phon-02",
        language="de-DE",
        category="ich-Laut vs ach-Laut",
        level="A1",
        title="El sonido de 'Buch' (Ach-Laut /x/)",
        target_text="Das Buch liegt auf dem Tisch.",
        ipa="das buːx liːkt aʊf deːm tɪʃ",
        phonetic_guide="Das buj liikt auf deem tish",
        phonetic_notes="x = ch velar (como jota española suave tras a/o/u), ʃ = sh",
        translation_es="El libro está sobre la mesa.",
        focus_phonemes=["x", "ʃ"],
        tip="Tras vocales posteriores (a, o, u), la 'ch' se pronuncia en la parte posterior (velar /x/), similar a la 'j' española suave.",
        articulation_type="velar",
    ),
    Exercise(
        id="de-phon-03",
        language="de-DE",
        category="ich-Laut vs ach-Laut",
        level="A2",
        title="Contraste directo Ich vs Ach",
        target_text="Ich suche ein einfaches Buch.",
        ipa="ɪç ˈzuːxə aɪn ˈaɪnfaχəs buːx",
        phonetic_guide="Ij zuuje ain áinfajes buuj",
        phonetic_notes="ç suave en 'Ich', x profunda en 'suche' y 'Buch'",
        translation_es="Busco un libro sencillo.",
        focus_phonemes=["ç", "x"],
        tip="Observa cómo cambia de /ç/ en 'Ich' a /x/ en 'suche' y 'Buch'.",
        articulation_type="palatal",
    ),
    Exercise(
        id="de-phon-04",
        language="de-DE",
        category="ich-Laut vs ach-Laut",
        level="B1",
        title="Tríada Fricativa: /ç/ vs /x/ vs /ʃ/",
        target_text="Ich möchte sechs frische Fische kochen.",
        ipa="ɪç ˈmœçtə zɛks ˈfʁɪʃə ˈfɪʃə ˈkɔxn̩",
        phonetic_guide="Ij méj-te zeks frishe fishe kojen",
        phonetic_notes="ö = boca en 'o' diciendo 'e', sechs = zeks con ks",
        translation_es="Quisiera cocinar seis pescados frescos.",
        focus_phonemes=["ç", "ʃ", "x"],
        tip="Diferencia con precisión: /ç/ en 'Ich/möchte', /ks/ en 'sechs', /ʃ/ en 'frische/Fische' y /x/ en 'kochen'.",
        articulation_type="palatal",
    ),
    # 2. Vocales con diéresis (Umlauts: ä, ö, ü)
    Exercise(
        id="de-umlaut-01",
        language="de-DE",
        category="Umlauts (ä, ö, ü)",
        level="A1",
        title="Umlaut Ö (/øː/, /œ/)",
        target_text="Ich möchte ein Brötchen möchten.",
        ipa="ɪç ˈmœçtə aɪn ˈbʁøːtçən",
        phonetic_guide="Ij méj-te ain bréet-jien méj-ten",
        phonetic_notes="ö (/øː/, /œ/) = labios redondeados en 'o' pronunciando 'e'",
        translation_es="Quisiera un panecillo.",
        focus_phonemes=["øː", "œ", "ç"],
        tip="Para pronunciar 'ö', coloca la boca en posición de decir 'o' (labios redondeados), pero intenta emitir una 'e'. ¡No abras los labios!",
        articulation_type="vowel",
    ),
    Exercise(
        id="de-umlaut-02",
        language="de-DE",
        category="Umlauts (ä, ö, ü)",
        level="A1",
        title="Umlaut Ü (/yː/, /ʏ/)",
        target_text="Für fünf Schüler gibt es Übungen.",
        ipa="fyːɐ̯ fʏnf ˈʃyːlɐ ɡɪpt ɛs ˈyːbʊŋən",
        phonetic_guide="Fiur fiunf shiuler gipt es iubunguen",
        phonetic_notes="ü (/yː/, /ʏ/) = labios en beso de 'u' pronunciando 'i'",
        translation_es="Para cinco alumnos hay ejercicios.",
        focus_phonemes=["yː", "ʏ"],
        tip="Para 'ü', pon los labios como si fueras a dar un beso (posición de 'u'), pero pronuncia 'i'.",
        articulation_type="vowel",
    ),
    Exercise(
        id="de-umlaut-03",
        language="de-DE",
        category="Umlauts (ä, ö, ü)",
        level="A2",
        title="Umlaut Ä (/ɛː/)",
        target_text="Die Mädchen wählen schöne Äpfel.",
        ipa="diː ˈmɛːtçən ˈvɛːlən ˈʃøːnə ˈɛpfəl",
        phonetic_guide="Dii méet-jien véelen shéene épfel",
        phonetic_notes="ä (/ɛː/) = 'e' abierta bajando la mandíbula; ö = 'e' con labios en 'o'",
        translation_es="Las chicas eligen manzanas hermosas.",
        focus_phonemes=["ɛː", "ç", "øː"],
        tip="La 'ä' es una 'e' abierta. Baja ligeramente la mandíbula inferior manteniendo la lengua adelante.",
        articulation_type="vowel",
    ),
    Exercise(
        id="de-umlaut-04",
        language="de-DE",
        category="Umlauts (ä, ö, ü)",
        level="A2",
        title="Contraste O base vs. Ö Umlaut",
        target_text="Ist es schon spät für dieses schöne Konzert?",
        ipa="ɪst ɛs ʃoːn ʃpɛːt fyːɐ̯ ˈdiːzəs ˈʃøːnə kɔnˈtsɛʁt",
        phonetic_guide="Ist es shoon shpéet fiur diizes shéene kontsert?",
        phonetic_notes="schon (o pura) vs schöne (ö redondeada), z = ts en Konzert",
        translation_es="¿Ya es tarde para este hermoso concierto?",
        focus_phonemes=["oː", "øː", "ʃ", "ts"],
        tip="Compara 'schon' (/oː/ posterior) con 'schöne' (/øː/ anterior redondeada con labios en óvalo cerrado).",
        articulation_type="vowel",
    ),
    # 3. Pares Mínimos Vocálicos Alemanes (Vocal Larga Tensa vs Corta Relajada)
    Exercise(
        id="de-vowel-len-01",
        language="de-DE",
        category="Pares Mínimos Vocálicos",
        level="A2",
        title="Larga /iː/ vs Corta /ɪ/ (bieten vs bitten)",
        target_text="Wir bieten Hilfe, wenn Sie höflich bitten.",
        ipa="viːɐ̯ ˈbiːtn̩ ˈhɪlfə vɛn ziː ˈhøːflɪç ˈbɪtn̩",
        phonetic_guide="Viir biiten jilfe, ven zii jéeflij biten",
        phonetic_notes="bieten (ii larga) vs bitten (i corta seca)",
        translation_es="Ofrecemos ayuda si usted pide cortésmente.",
        focus_phonemes=["iː", "ɪ", "øː", "ç"],
        tip="En 'bieten' la 'ie' es larga, tensa y sonriente (/iː/). En 'bitten' la 'i' es corta y relajada (/ɪ/).",
        articulation_type="vowel",
    ),
    Exercise(
        id="de-vowel-len-02",
        language="de-DE",
        category="Pares Mínimos Vocálicos",
        level="A2",
        title="Larga /eː/ vs Corta /ɛ/ (Beet vs Bett)",
        target_text="Die Blumen im Beet und das weiche Bett.",
        ipa="diː ˈbluːmən ɪm beːt ʊnt das ˈvaɪçə bɛt",
        phonetic_guide="Dii bluumen im beet unt das vaíje bet",
        phonetic_notes="Beet (ee larga) vs Bett (e corta y seca)",
        translation_es="Las flores en el parterre y la cama blanda.",
        focus_phonemes=["eː", "ɛ", "ç", "t"],
        tip="'Beet' tiene una /eː/ larga y cerrada; 'Bett' tiene una /ɛ/ corta, abierta y seca.",
        articulation_type="vowel",
    ),
    Exercise(
        id="de-vowel-len-03",
        language="de-DE",
        category="Pares Mínimos Vocálicos",
        level="A2",
        title="Larga /yː/ vs Corta /ʏ/ (fühlen vs füllen)",
        target_text="Wir fühlen die Kälte und füllen die Gläser.",
        ipa="viːɐ̯ ˈfyːlən diː ˈkɛltə ʊnt ˈfʏlən diː ˈɡlɛːzɐ",
        phonetic_guide="Viir fiulen dii kélte unt fiulen dii gléezer",
        phonetic_notes="fühlen (ü sostenida larga) vs füllen (ü corta rápida)",
        translation_es="Sentimos el frío y llenamos los vasos.",
        focus_phonemes=["yː", "ʏ", "ɛː"],
        tip="'fühlen' tiene una 'ü' larga y tensa (/yː/). En 'füllen' la doble 'll' acorta la vocal a /ʏ/ relajada.",
        articulation_type="vowel",
    ),
    # 4. Sibilantes y Fricativas Alemanas (/s/ sorda vs /z/ sonora vs /ts/)
    Exercise(
        id="de-s-z-01",
        language="de-DE",
        category="Sibilantes y Fricativas",
        level="B1",
        title="Sonora /z/ vs Sorda /s/ (reisen vs reißen)",
        target_text="Sie reisen gern und reißen alte Zettel ab.",
        ipa="ziː ˈʁaɪzn̩ ɡɛʁn ʊnt ˈʁaɪsn̩ ˈaltə ˈtsɛtl̩ ap",
        phonetic_guide="Zii ráizen guern unt ráisen álte tsétel ap",
        phonetic_notes="reisen (s vibrada como abeja) vs reißen (s sorda normal), Zettel = ts",
        translation_es="Ellos viajan con gusto y rompen notas viejas.",
        focus_phonemes=["z", "s", "ts"],
        tip="'reisen' tiene 's' intervocálica sonora (/z/, con vibración laríngea como abeja). 'reißen' (ß) es totalmente sorda (/s/).",
        articulation_type="alveolar",
    ),
    # 5. Auslautverhärtung (Ensordecimiento final de consonantes)
    Exercise(
        id="de-auslaut-01",
        language="de-DE",
        category="Auslautverhärtung (Finales)",
        level="A2",
        title="Consonantes finales duras (d->t, b->p, g->k)",
        target_text="Guten Tag, das ist ein schönes Bild!",
        ipa="ˈɡuːtn taːk das ɪst aɪn ˈʃøːnəs bɪlt",
        phonetic_guide="Guuten taak, das ist ain shéenes bilt!",
        phonetic_notes="Tag termina en sonido /k/, Bild termina en sonido /t/",
        translation_es="¡Buen día, esta es una hermosa imagen!",
        focus_phonemes=["k", "t", "p"],
        tip="Al final de palabra o sílaba en alemán, 'Tag' termina en sonido sordo /k/, y 'Bild' termina en sonido /t/ sin vibrar.",
        articulation_type="alveolar",
    ),
    # 6. R Alemana (Uvular /ʁ/ vs Vocalizada /ɐ/)
    Exercise(
        id="de-r-01",
        language="de-DE",
        category="La 'R' Alemana",
        level="A2",
        title="R uvular inicial vs R vocalizada final",
        target_text="Der Lehrer trinkt klares Wasser.",
        ipa="deːɐ̯ ˈleːʁɐ tʁɪŋkt ˈklaːʁəs ˈvasɐ",
        phonetic_guide="Dee-a lee-ra tringt klaares vasa",
        phonetic_notes="ʁ = r uvular campanilla, ɐ = r final suena como 'a' relajada",
        translation_es="El profesor bebe agua clara.",
        focus_phonemes=["ʁ", "ɐ"],
        tip="Al final de palabra (-er, der), la 'r' se vocaliza en /ɐ/ (suena como una 'a' corta y relajada). Al inicio, vibra suavemente en la campanilla.",
        articulation_type="uvular",
    ),
    # 7. Zungenbrecher (Trabalenguas)
    Exercise(
        id="de-tongue-twister-01",
        language="de-DE",
        category="Zungenbrecher (Trabalenguas)",
        level="B1",
        title="Zungenbrecher de 'Fischers Fritz'",
        target_text="Fischers Fritz fischt frische Fische.",
        ipa="ˈfɪʃɐs fʁɪts fɪʃt ˈfʁɪʃə ˈfɪʃə",
        phonetic_guide="Fisherz frits fisht frishe fishe",
        phonetic_notes="ʃ = sonido sh, ts = ts en Fritz",
        translation_es="Fritz el pescador pesca peces frescos.",
        focus_phonemes=["ʃ", "ts", "ʁ", "ɪ"],
        tip="Combina con agilidad la fricativa postalveolar /ʃ/ con la africada /ts/ y la R uvular /ʁ/.",
        articulation_type="postalveolar",
    ),
    # 8. Vida Cotidiana A1-B1
    Exercise(
        id="de-daily-01",
        language="de-DE",
        category="Vida Cotidiana",
        level="A1",
        title="Pedir en una cafetería",
        target_text="Entschuldigung, kann ich bitte einen Kaffee haben?",
        ipa="ɛntˈʃʊldɪɡʊŋ kan ɪç ˈbɪtə ˈaɪnən ˈkafeː ˈhaːbn̩",
        phonetic_guide="Ent-shúldigung, kan ij bite áinen kafee jaaben?",
        phonetic_notes="ʃ = sh en Entschuldigung, ç = ch suave en ich",
        translation_es="Disculpe, ¿puedo pedir un café por favor?",
        focus_phonemes=["ç", "ʃ"],
        tip="Presta atención a la fluidez y a la unión de palabras en preguntas de cortesía.",
        articulation_type="palatal",
    ),
    Exercise(
        id="de-daily-02",
        language="de-DE",
        category="Vida Cotidiana",
        level="B1",
        title="Expresar opinión con oraciones subordinadas",
        target_text="Ich glaube, dass wir heute noch pünktlich ankommen.",
        ipa="ɪç ˈɡlaʊbə das viːɐ̯ ˈhɔɪtə nɔx ˈpʏŋktlɪç ˈankɔmən",
        phonetic_guide="Ij gláube, das viir jóite noj piúnktlij ánkomen",
        phonetic_notes="ç suave en ich/pünktlich, x en noch, ü en pünktlich",
        translation_es="Creo que hoy todavía llegaremos puntuales.",
        focus_phonemes=["ç", "x", "ʏ"],
        tip="Cuida la entonación que desciende al final de la cláusula subordinada y la pronunciación de 'pünktlich'.",
        articulation_type="palatal",
    ),
    # =========================================================================
    # INGLÉS (en-US)
    # =========================================================================
    # 1. Sonidos TH (/θ/ sordo vs /ð/ sonoro)
    Exercise(
        id="en-th-01",
        language="en-US",
        category="TH Sounds (/θ/ vs /ð/)",
        level="A1",
        title="Unvoiced TH (/θ/ como en 'think')",
        target_text="I think thirty three things are thrilling.",
        ipa="aɪ θɪŋk ˈθɜːti θriː θɪŋz ɑːr ˈθrɪlɪŋ",
        phonetic_guide="Ai zink zer-ti zrii zings ar zriling",
        phonetic_notes="θ = th sorda (como la 'z' española peninsular en zapato, sin vibrar)",
        translation_es="Creo que treinta y tres cosas son emocionantes.",
        focus_phonemes=["θ"],
        tip="Coloca la punta de la lengua suavemente entre los dientes frontales e impulsa aire sin vibrar las cuerdas vocales.",
        articulation_type="dental",
    ),
    Exercise(
        id="en-th-02",
        language="en-US",
        category="TH Sounds (/θ/ vs /ð/)",
        level="A1",
        title="Voiced TH (/ð/ como en 'this')",
        target_text="This is their father and mother.",
        ipa="ðɪs ɪz ðɛr ˈfɑːðər ænd ˈmʌðər",
        phonetic_guide="Dhis iz dher faa-dher end ma-dher",
        phonetic_notes="ð = th sonora (lengua entre dientes con vibración, como una d suave)",
        translation_es="Este es el padre y la madre de ellos.",
        focus_phonemes=["ð"],
        tip="Misma posición interdental de la lengua, pero haciendo vibrar activamente la garganta (cuerdas vocales).",
        articulation_type="dental",
    ),
    Exercise(
        id="en-th-03",
        language="en-US",
        category="TH Sounds (/θ/ vs /ð/)",
        level="A2",
        title="Contraste directo: Breath (/θ/) vs. Breathe (/ð/)",
        target_text="Take a deep breath and breathe calmly.",
        ipa="teɪk ə diːp brɛθ ænd briːð ˈkɑːmli",
        phonetic_guide="Teik e diip brez end briidh kaam-li",
        phonetic_notes="breath (termina en z sorda) vs breathe (termina en d suave vibrada)",
        translation_es="Toma una respiración profunda y respira con calma.",
        focus_phonemes=["θ", "ð", "iː", "ɛ"],
        tip="'Breath' termina en /θ/ sorda; 'breathe' tiene vocal larga /iː/ y termina en /ð/ sonora con vibración.",
        articulation_type="dental",
    ),
    # 2. Pares Mínimos Vocálicos (Interferencia común del español)
    Exercise(
        id="en-vowels-01",
        language="en-US",
        category="Pares Mínimos Vocálicos",
        level="A2",
        title="Sheep /iː/ vs Ship /ɪ/",
        target_text="The big sheep sleeps on the green hill.",
        ipa="ðə bɪɡ ʃiːp sliːps ɑːn ðə ɡriːn hɪl",
        phonetic_guide="Dhe big shiip sliips on dhe griin jil",
        phonetic_notes="iː = i larga tensa (sheep/sleeps), ɪ = i corta relajada (big/hill)",
        translation_es="La gran oveja duerme sobre la colina verde.",
        focus_phonemes=["iː", "ɪ"],
        tip="En 'sleeps' la vocal es tensa y sonriente (/iː/). En 'big' e 'hill', la vocal es relajada, corta y central (/ɪ/).",
        articulation_type="vowel",
    ),
    Exercise(
        id="en-vowels-02",
        language="en-US",
        category="Pares Mínimos Vocálicos",
        level="A2",
        title="Cat /æ/ vs Cut /ʌ/",
        target_text="The black cat jumped over the cup.",
        ipa="ðə blæk kæt dʒʌmpt ˈoʊvər ðə kʌp",
        phonetic_guide="Dhe blek ket dyompt ou-ver dhe cop",
        phonetic_notes="æ = a abierta (entre a y e en cat), ʌ = u corta central (cup)",
        translation_es="El gato negro saltó sobre la taza.",
        focus_phonemes=["æ", "ʌ"],
        tip="/æ/ requiere abrir la mandíbula hacia abajo como diciendo 'a' con lengua de 'e'. /ʌ/ es neutra y breve en el centro.",
        articulation_type="vowel",
    ),
    Exercise(
        id="en-vowels-03",
        language="en-US",
        category="Pares Mínimos Vocálicos",
        level="A2",
        title="Pull /ʊ/ vs. Pool /uː/",
        target_text="Please pull the rope before you jump in the pool.",
        ipa="pliːz pʊl ðə roʊp bɪˈfɔːr juː dʒʌmp ɪn ðə puːl",
        phonetic_guide="Pliiz pul dhe roup bi-for yu dyamp in dhe puul",
        phonetic_notes="pull (ʊ corta relajada) vs pool (uu larga redonda)",
        translation_es="Por favor jala la cuerda antes de saltar a la piscina.",
        focus_phonemes=["ʊ", "uː"],
        tip="'Pull' usa /ʊ/ corta y relajada (labios semi-redondeados). 'Pool' usa /uː/ tensa, larga y con labios en círculo cerrado.",
        articulation_type="vowel",
    ),
    Exercise(
        id="en-vowels-04",
        language="en-US",
        category="Pares Mínimos Vocálicos",
        level="B1",
        title="Cot /ɑː/ vs. Caught /ɔː/ vs. Coat /oʊ/",
        target_text="Paul caught a cold and put on his warm coat.",
        ipa="pɔːl kɑːt ə koʊld ænd pʊt ɑːn hɪz wɔːrm koʊt",
        phonetic_guide="Pool coot e could end put on jiz vorm cout",
        phonetic_notes="caught (ɔː abierta) vs coat (oʊ diptongo ou)",
        translation_es="Paul se resfrió y se puso su abrigo cálido.",
        focus_phonemes=["ɔː", "oʊ", "ɑː"],
        tip="No sustituyas todas por la 'o' española: /ɔː/ es abierta y posterior, mientras que /oʊ/ en 'coat' es un diptongo dinámico.",
        articulation_type="vowel",
    ),
    # 3. Labiodental V (/v/) vs Bilabial B (/b/)
    Exercise(
        id="en-b-v-01",
        language="en-US",
        category="V vs B",
        level="A1",
        title="Distinguiendo V (/v/) de B (/b/)",
        target_text="Very best friends travel by van and boat.",
        ipa="ˈvɛri bɛst frɛndz ˈtrævəl baɪ væn ænd boʊt",
        phonetic_guide="Véri best frendz trável bai van end bout",
        phonetic_notes="v = dientes superiores rozando labio inferior con vibración, no b",
        translation_es="Los mejores amigos viajan en furgoneta y barco.",
        focus_phonemes=["v", "b"],
        tip="En español no diferenciamos B de V. En inglés, para la 'V' tus dientes superiores DEBEN tocar el labio inferior con fricción acústica continua.",
        articulation_type="labiodental",
    ),
    # 4. Semivocal W (/w/) vs Labiodental V (/v/)
    Exercise(
        id="en-w-v-01",
        language="en-US",
        category="W vs V",
        level="A2",
        title="West (/w/) vs. Vest (/v/)",
        target_text="We went west wearing very warm vests.",
        ipa="wiː wɛnt wɛst ˈwɛrɪŋ ˈvɛri wɔːrm vɛsts",
        phonetic_guide="Uii uent uest uéring véri uorm vests",
        phonetic_notes="w = labios en u redonda sin tocar dientes vs v = dientes en labio",
        translation_es="Fuimos al oeste vistiendo chalecos muy abrigados.",
        focus_phonemes=["w", "v"],
        tip="Para 'W' (/w/), los dientes NUNCA tocan los labios (redondea como una 'u'). Para 'V' (/v/), los dientes superiores rozan el labio inferior.",
        articulation_type="labiodental",
    ),
    # 5. Líquidas y Aproximantes (R rótica /ɹ/ vs L lateral /l/)
    Exercise(
        id="en-r-l-01",
        language="en-US",
        category="Líquidas (R vs L)",
        level="A2",
        title="American R (/ɹ/) vs. L (/l/)",
        target_text="The red light turns right along the long river.",
        ipa="ðə rɛd laɪt tɜːrnz raɪt əˈlɔːŋ ðə lɔːŋ ˈrɪvər",
        phonetic_guide="Dhe red lait ternz rait e-long dhe long ri-ver",
        phonetic_notes="r americana = lengua curvada hacia atrás sin tocar paladar",
        translation_es="La luz roja gira a la derecha a lo largo del río largo.",
        focus_phonemes=["r", "l"],
        tip="Para la 'R' en inglés americano (/ɹ/), la lengua se curva hacia atrás sin tocar el paladar ni vibrar. Para la 'L' (/l/), la punta toca firmemente detrás de los dientes.",
        articulation_type="alveolar",
    ),
    # 6. Terminaciones Morfológicas Gramaticales (-ed endings: /t/, /d/, /ɪd/)
    Exercise(
        id="en-endings-ed-01",
        language="en-US",
        category="Terminaciones Gramaticales (-ed)",
        level="B1",
        title="Pasado Regular -ed: /t/, /d/ e /ɪd/",
        target_text="She walked to the park, played music, and waited.",
        ipa="ʃiː wɔːkt tuː ðə pɑːrk pleɪd ˈmjuːzɪk ænd ˈweɪtɪd",
        phonetic_guide="Shii uokt tu dhe park, pleid miúzik, end uéitid",
        phonetic_notes="walked (/t/), played (/d/), waited (/ɪd/)",
        translation_es="Ella caminó al parque, tocó música y esperó.",
        focus_phonemes=["t", "d", "ɪd"],
        tip="'walked' termina en sonido seco /t/; 'played' termina en sonido sonoro /d/; solo 'waited' (tras sonido t/d) añade una sílaba extra /ɪd/.",
        articulation_type="alveolar",
    ),
    # 7. Tongue Twisters (Trabalenguas en Inglés)
    Exercise(
        id="en-tongue-twister-01",
        language="en-US",
        category="Tongue Twisters (Trabalenguas)",
        level="B1",
        title="She sells seashells (/s/ vs /ʃ/)",
        target_text="She sells seashells by the seashore.",
        ipa="ʃiː sɛlz ˈsiːʃɛlz baɪ ðə ˈsiːʃɔːr",
        phonetic_guide="Shii selz sii-shelz bai dhe sii-shor",
        phonetic_notes="s = s dental normal vs ʃ = sonido sh",
        translation_es="Ella vende conchas marinas a la orilla del mar.",
        focus_phonemes=["ʃ", "s", "z"],
        tip="Entrena la transición veloz entre la sibilante alveolar /s/ en 'sells/sea' y la postalveolar /ʃ/ en 'she/shells/shore'.",
        articulation_type="postalveolar",
    ),
    # 8. Conversación Cotidiana
    Exercise(
        id="en-daily-01",
        language="en-US",
        category="Conversación Cotidiana",
        level="B1",
        title="Presentación profesional y proyectos",
        target_text="I would really appreciate your feedback on this project.",
        ipa="aɪ wʊd ˈrɪəli əˈpriːʃieɪt jʊər ˈfiːdbæk ɑːn ðɪs ˈprɑːdʒɛkt",
        phonetic_guide="Ai uud ríi-li e-príi-shieit yor fíid-bek on dhis pródyeckt",
        phonetic_notes="ʃ = sh en appreciate, ð = th en this, æ = a en feedback",
        translation_es="Realmente agradecería tus comentarios sobre este proyecto.",
        focus_phonemes=["ʃ", "ð", "æ"],
        tip="Enfócate en la fluidez del ritmo y la reducción de sonidos no acentuados ('would', 'your').",
        articulation_type="postalveolar",
    ),
    # =========================================================================
    # ALEMÁN - ESCRITURA (Schreiben) A1, A2, B1
    # =========================================================================
    # =========================================================================
    # ALEMÁN - ESCRITURA (Writing) A1, A2, B1
    # =========================================================================
    Exercise(
        id="de-write-01",
        language="de-DE",
        category="Presentación y Origen",
        level="A1",
        skill_type="writing",
        title="Presentación y Lugar de Residencia",
        prompt="✍️ Escribe en alemán: 'Hola, me llamo Carlos y vivo en Berlín.'",
        target_text="Hallo, ich heiße Carlos und ich wohne in Berlin.",
        translation_es="Hola, me llamo Carlos y vivo en Berlín.",
        tip="Recuerda conjugar los verbos en primera persona: 'ich heiße' y 'ich wohne'.",
        vocabulary_breakdown={
            "heißen": "llamarse (ich heiße, du heißt)",
            "wohnen": "vivir / residir (ich wohne)",
            "und": "y (conjunción)",
            "in": "en (preposición de lugar)",
        },
        grammar_note="En alemán los nombres propios y las ciudades se escriben con mayúscula inicial.",
    ),
    Exercise(
        id="de-write-02",
        language="de-DE",
        category="Artículos y Acusativo",
        level="A1",
        skill_type="writing",
        title="Mascotas y Objeto Directo (Akkusativ)",
        prompt="✍️ Traduce al alemán: 'Tengo un perro y una gata.' (Ojo con el artículo de perro: der Hund)",
        target_text="Ich habe einen Hund und eine Katze.",
        translation_es="Tengo un perro y una gata.",
        tip="El verbo 'haben' rige Acusativo. El masculino 'der Hund' se convierte en 'einen Hund', mientras el femenino 'eine Katze' se mantiene.",
        vocabulary_breakdown={
            "haben": "tener (ich habe)",
            "der Hund": "el perro ➔ acusativo: einen Hund",
            "die Katze": "la gata / gato hembra ➔ acusativo: eine Katze",
        },
        grammar_note="En alemán TODOS los sustantivos (Hund, Katze, etc.) se escriben con mayúscula inicial obligatoria.",
    ),
    Exercise(
        id="de-write-03",
        language="de-DE",
        category="Rutinas y Verbos Separables",
        level="A1",
        skill_type="writing",
        title="Levantarse por la mañana (aufstehen)",
        prompt="✍️ Escribe en alemán: 'Me levanto todos los días a las siete.' (Verbo separable: aufstehen)",
        target_text="Ich stehe jeden Tag um sieben Uhr auf.",
        translation_es="Me levanto todos los días a las siete.",
        tip="En verbos separables (aufstehen), el prefijo 'auf' va al final de la oración: 'stehe ... auf'.",
        vocabulary_breakdown={
            "aufstehen": "levantarse (trennbare Verben: stehe ... auf)",
            "jeden Tag": "todos los días (acusativo de tiempo)",
            "um sieben Uhr": "a las siete en punto",
        },
        grammar_note="El prefijo de los verbos separables siempre se coloca en la última posición de la cláusula principal.",
    ),
    Exercise(
        id="de-write-04",
        language="de-DE",
        category="Restaurante y Pedidos",
        level="A1",
        skill_type="writing",
        title="Pedir en un café con cortesía",
        prompt="✍️ Escribe con cortesía en alemán: 'Me gustaría tomar una taza de café, por favor.'",
        target_text="Ich möchte bitte eine Tasse Kaffee trinken.",
        translation_es="Me gustaría tomar una taza de café, por favor.",
        tip="Usa el modal de cortesía 'möchte' en posición 2 y el verbo 'trinken' en infinitivo al final.",
        vocabulary_breakdown={
            "möchte": "me gustaría / quisiera",
            "die Tasse": "la taza",
            "der Kaffee": "el café",
            "trinken": "beber / tomar",
            "bitte": "por favor",
        },
        grammar_note="'möchte' exige que el segundo verbo vaya en infinitivo al final absoluto de la oración.",
    ),
    Exercise(
        id="de-write-05",
        language="de-DE",
        category="Familia y Posesivos",
        level="A1",
        skill_type="writing",
        title="Hablar de la familia",
        prompt="✍️ Traduce al alemán: 'Mi hermano vive en Múnich y mi hermana estudia allí.'",
        target_text="Mein Bruder wohnt in München und meine Schwester studiert dort.",
        translation_es="Mi hermano vive en Múnich y mi hermana estudia allí.",
        tip="'Mein Bruder' (masculino) vs 'Meine Schwester' (femenino con terminación -e).",
        vocabulary_breakdown={
            "mein / meine": "mi (posesivo masculino / femenino)",
            "der Bruder": "el hermano",
            "die Schwester": "la hermana",
            "studieren": "estudiar en la universidad",
            "dort": "allí / allá",
        },
        grammar_note="Los adjetivos posesivos concuerdan en género, número y caso con el sustantivo que acompañan.",
    ),
    Exercise(
        id="de-write-06",
        language="de-DE",
        category="Pasado Perfekt",
        level="A2",
        skill_type="writing",
        title="Acciones Pasadas Cotidianas",
        prompt="✍️ Escribe en pasado (Perfekt): 'Ayer compré un café.'",
        target_text="Gestern habe ich einen Kaffee gekauft.",
        translation_es="Ayer compré un café.",
        tip="Estructura del Perfekt: Verbo auxiliar (habe) en posición 2 y participio (gekauft) al final.",
        vocabulary_breakdown={
            "gestern": "ayer",
            "kaufen": "comprar (participio: gekauft)",
            "der Kaffee": "el café ➔ acusativo: einen Kaffee",
        },
        grammar_note="Si la frase empieza con 'Gestern', el verbo va en posición 2 y el sujeto pasa a posición 3 (inversión).",
    ),
    Exercise(
        id="de-write-07",
        language="de-DE",
        category="Oraciones Subordinadas (weil)",
        level="A2",
        skill_type="writing",
        title="Dar Razones con 'weil'",
        prompt="✍️ Une con 'weil' (porque): 'Aprendo alemán porque es interesante.'",
        target_text="Ich lerne Deutsch, weil es interessant ist.",
        translation_es="Aprendo alemán porque es interesante.",
        tip="La conjunción subordinante 'weil' envía el verbo conjugado ('ist') al final absoluto de la cláusula.",
        vocabulary_breakdown={
            "lernen": "aprender",
            "weil": "porque (conjunción subordinante)",
            "interessant": "interesante",
            "ist": "es / está (verbo sein)",
        },
        grammar_note="Antes de 'weil' siempre se escribe una coma (, weil ... verbo conjugado al final).",
    ),
    Exercise(
        id="de-write-08",
        language="de-DE",
        category="Verbos Modales en Pasado (Präteritum)",
        level="A2",
        skill_type="writing",
        title="Obligaciones laborales en pasado",
        prompt="✍️ Escribe en alemán: 'Tuve que trabajar hasta tarde ayer.' (Modal: müssen en Präteritum)",
        target_text="Ich musste gestern bis spät arbeiten.",
        translation_es="Tuve que trabajar hasta tarde ayer.",
        tip="El pasado simple de 'müssen' para 'ich' es 'musste' (sin umlaut). El infinitivo 'arbeiten' va al final.",
        vocabulary_breakdown={
            "musste": "tuve que / debía (Präteritum de müssen)",
            "bis spät": "hasta tarde",
            "arbeiten": "trabajar",
        },
        grammar_note="En alemán los verbos modales se usan casi exclusivamente en Präteritum al hablar en pasado.",
    ),
    Exercise(
        id="de-write-09",
        language="de-DE",
        category="Preposiciones con Dativo",
        level="A2",
        skill_type="writing",
        title="Desplazarse con transporte (mit + Dativo)",
        prompt="✍️ Escribe en alemán: 'Voy al trabajo en tren todos los días.' (der Zug ➔ Dativo con 'mit')",
        target_text="Ich fahre jeden Tag mit dem Zug zur Arbeit.",
        translation_es="Voy al trabajo en tren todos los días.",
        tip="'mit' siempre exige Dativo. El masculino 'der Zug' cambia a 'dem Zug'. 'zur' es la contracción de 'zu der'.",
        vocabulary_breakdown={
            "fahren": "ir en vehículo / viajar",
            "mit dem Zug": "en tren (Dativo masculino)",
            "die Arbeit": "el trabajo ➔ zur Arbeit (zu + der)",
        },
        grammar_note="Las preposiciones fijas de dativo son: aus, bei, mit, nach, seit, von, zu.",
    ),
    Exercise(
        id="de-write-10",
        language="de-DE",
        category="Preposiciones Mixtas (Wechselpräpositionen)",
        level="A2",
        skill_type="writing",
        title="Ubicación estática vs Movimiento (in)",
        prompt="✍️ Escribe en alemán con acusativo de movimiento: 'Pongo el libro en la mesa.' (der Tisch)",
        target_text="Ich lege das Buch auf den Tisch.",
        translation_es="Pongo el libro sobre la mesa.",
        tip="Acción/movimiento (¿adónde? = Wohin?) exige Acusativo: 'auf den Tisch'.",
        vocabulary_breakdown={
            "legen": "poner / colocar en posición horizontal",
            "das Buch": "el libro",
            "auf den Tisch": "sobre la mesa (Acusativo masculino de dirección)",
        },
        grammar_note="Las Wechselpräpositionen rigen Acusativo para destino/movimiento (Wohin?) y Dativo para posición fija (Wo?).",
    ),
    Exercise(
        id="de-write-11",
        language="de-DE",
        category="Cortesía y Negocios (B1)",
        level="B1",
        skill_type="writing",
        title="Solicitud Formal de Cita",
        prompt="✍️ Escribe con cortesía formal: 'Me gustaría acordar una cita, por favor.'",
        target_text="Ich möchte bitte einen Termin vereinbaren.",
        translation_es="Me gustaría acordar una cita, por favor.",
        tip="Usa 'möchte' + infinitivo al final ('vereinbaren'). 'Der Termin' pasa a 'einen Termin' en acusativo.",
        vocabulary_breakdown={
            "möchte": "me gustaría (forma de cortesía)",
            "der Termin": "la cita profesional o médica",
            "vereinbaren": "pactar / agendar",
            "bitte": "por favor",
        },
        grammar_note="Los verbos modales colocan el segundo verbo en infinitivo al final de la frase.",
    ),
    Exercise(
        id="de-write-12",
        language="de-DE",
        category="Konjunktiv II (Hipotético y Deseos)",
        level="B1",
        skill_type="writing",
        title="Situación hipotética con 'Wenn'",
        prompt="✍️ Traduce usando Konjunktiv II: 'Si tuviera más tiempo, viajaría a Alemania.'",
        target_text="Wenn ich mehr Zeit hätte, würde ich nach Deutschland reisen.",
        translation_es="Si tuviera más tiempo, viajaría a Alemania.",
        tip="'hätte' (tuviera) va al final de la subordinada. La cláusula principal inicia con el verbo 'würde ich...'.",
        vocabulary_breakdown={
            "wenn": "si condicional",
            "hätte": "tuviera / tuviese (Konjunktiv II de haben)",
            "würde reisen": "viajaría (forma compuesta de Konjunktiv II)",
            "nach Deutschland": "a Alemania",
        },
        grammar_note="El Konjunktiv II expresa deseos irreales y condiciones hipotéticas.",
    ),
    Exercise(
        id="de-write-13",
        language="de-DE",
        category="Oraciones de Relativo (Relativsätze)",
        level="B1",
        skill_type="writing",
        title="Identificar a una persona con pronombre relativo",
        prompt="✍️ Traduce en alemán: 'Ese es el hombre que me ayudó ayer.' (der Mann ➔ sujeto der)",
        target_text="Das ist der Mann, der mir gestern geholfen hat.",
        translation_es="Ese es el hombre que me ayudó ayer.",
        tip="El pronombre relativo masculino en nominativo es 'der'. El verbo auxiliar ('hat') va al final de la cláusula.",
        vocabulary_breakdown={
            "der Mann": "el hombre",
            "der": "que / el cual (pronombre relativo nominativo)",
            "mir": "a mí (Dativo con helfen)",
            "geholfen hat": "ayudó / ha ayudado",
        },
        grammar_note="'helfen' siempre rige objeto en Dativo (helfen + mir/dir/ihm).",
    ),
    Exercise(
        id="de-write-14",
        language="de-DE",
        category="Voz Pasiva (Passiv Präsens)",
        level="B1",
        skill_type="writing",
        title="Procesos y Construcción",
        prompt="✍️ Escribe en pasiva: 'El nuevo puente se construirá el próximo año.' (wird gebaut)",
        target_text="Die neue Brücke wird nächstes Jahr gebaut.",
        translation_es="El nuevo puente es construido / se construye el próximo año.",
        tip="Estructura de la pasiva: werden conjugado ('wird') + participio al final ('gebaut').",
        vocabulary_breakdown={
            "die Brücke": "el puente (femenino en alemán)",
            "wird": "es / se (auxiliar de pasiva werden)",
            "nächstes Jahr": "el próximo año",
            "gebaut": "construido (participio de bauen)",
        },
        grammar_note="La pasiva de proceso en alemán se forma con 'werden + Partizip II'.",
    ),
    # =========================================================================
    # ALEMÁN - COMPRENSIÓN AUDITIVA (Hören) - Goethe-Zertifikat A1: Start Deutsch 1
    # =========================================================================

    # --- A1 (Supervivencia: Máximo ~650 palabras frecuentes, números 1-10, bebidas, horas en punto) ---
    Exercise(
        id="de-listen-a1-01",
        language="de-DE",
        category="En la Cafetería (A1)",
        level="A1",
        skill_type="listening",
        title="Pedir una bebida",
        prompt="👂 Escucha el audio nativo y responde: ¿Qué bebida pide el cliente?",
        target_text="Guten Tag! Einen Kaffee mit Milch, bitte.",
        translation_es="¡Buen día! Un café con leche, por favor.",
        tip="Identifica las palabras esenciales: 'Kaffee' (café) y 'Milch' (leche).",
        options=[
            "Un café con leche (Kaffee mit Milch)",
            "Un té con limón (Tee mit Zitrone)",
            "Una botella de agua mineral (Wasser)",
        ],
        correct_option_index=0,
        vocabulary_breakdown={
            "der Kaffee": "el café",
            "die Milch": "la leche",
            "bitte": "por favor",
            "Guten Tag": "buenos días / hola",
        },
        grammar_note="En alemán 'einen Kaffee' está en acusativo masculino porque es el objeto que se pide.",
    ),
    Exercise(
        id="de-listen-a1-02",
        language="de-DE",
        category="Presentación y Origen (A1)",
        level="A1",
        skill_type="listening",
        title="¿De dónde es Carlos?",
        prompt="👂 Escucha con atención: ¿De qué país proviene Carlos?",
        target_text="Hallo, ich heiße Carlos und ich komme aus Spanien.",
        translation_es="Hola, me llamo Carlos y vengo de España.",
        tip="Escucha la frase de origen: 'komme aus...' seguida del país.",
        options=[
            "De España (aus Spanien)",
            "De Alemania (aus Deutschland)",
            "De México (aus Mexiko)",
        ],
        correct_option_index=0,
        vocabulary_breakdown={
            "ich heiße": "me llamo",
            "ich komme aus": "vengo de / soy de",
            "Spanien": "España",
        },
        grammar_note="Para indicar tu país de origen en alemán siempre se usa la preposición 'aus'.",
    ),
    Exercise(
        id="de-listen-a1-03",
        language="de-DE",
        category="Compras y Precios Básicos (A1)",
        level="A1",
        skill_type="listening",
        title="El precio del pan en la panadería",
        prompt="👂 Escucha el precio: ¿Cuánto cuesta el pan?",
        target_text="Das frische Brot kostet zwei Euro.",
        translation_es="El pan fresco cuesta dos euros.",
        tip="Concéntrate en el número básico 'zwei' (2) antes de 'Euro'.",
        options=[
            "2,00 € (zwei Euro)",
            "5,00 € (fünf Euro)",
            "10,00 € (zehn Euro)",
        ],
        correct_option_index=0,
        vocabulary_breakdown={
            "das Brot": "el pan",
            "kostet": "cuesta (verbo kosten)",
            "zwei": "dos (2)",
            "Euro": "euro",
        },
    ),
    Exercise(
        id="de-listen-a1-04",
        language="de-DE",
        category="Horas y Citas Simples (A1)",
        level="A1",
        skill_type="listening",
        title="¿A qué hora llega el autobús?",
        prompt="👂 Escucha la hora indicada: ¿Cuándo llega el autobús?",
        target_text="Der Bus kommt genau um acht Uhr.",
        translation_es="El autobús llega exactamente a las ocho en punto.",
        tip="En nivel A1 las horas formales se dicen con 'um [número] Uhr'.",
        options=[
            "A las 6:00 (um sechs Uhr)",
            "A las 8:00 (um acht Uhr)",
            "A las 10:00 (um zehn Uhr)",
        ],
        correct_option_index=1,
        vocabulary_breakdown={
            "der Bus": "el autobús",
            "kommt": "viene / llega (kommen)",
            "acht Uhr": "ocho en punto",
            "um": "a las (para horas)",
        },
    ),
    Exercise(
        id="de-listen-a1-05",
        language="de-DE",
        category="Días de la Semana (A1)",
        level="A1",
        skill_type="listening",
        title="¿Qué día es la clase de alemán?",
        prompt="👂 Escucha el día mencionado: ¿Cuándo es el curso?",
        target_text="Unser Deutschkurs ist am Montag.",
        translation_es="Nuestro curso de alemán es el lunes.",
        tip="Los días de la semana en alemán van precedidos de 'am' (am Montag, am Dienstag...).",
        options=[
            "El lunes (am Montag)",
            "El miércoles (am Mittwoch)",
            "El viernes (am Freitag)",
        ],
        correct_option_index=0,
        vocabulary_breakdown={
            "unser": "nuestro",
            "der Deutschkurs": "el curso de alemán",
            "am Montag": "el lunes",
        },
        grammar_note="Para días de la semana y partes del día (excepto la noche) se usa la preposición 'am'.",
    ),

    # --- A2 (Plataforma: Oraciones compuestas, cuartos de hora, declinaciones) ---
    Exercise(
        id="de-listen-a2-01",
        language="de-DE",
        category="Horarios y Cuartos de Hora (A2)",
        level="A2",
        skill_type="listening",
        title="¿A qué hora es la reunión?",
        prompt="👂 Escucha el audio nativo y selecciona la hora exacta:",
        target_text="Das Treffen beginnt um Viertel vor acht.",
        translation_es="La reunión comienza a las ocho menos cuarto (7:45).",
        tip="Presta atención a 'Viertel vor' (un cuarto antes de...) vs 'Viertel nach'.",
        options=[
            "7:45 (Viertel vor acht)",
            "8:15 (Viertel nach acht)",
            "8:45 (Viertel vor neun)",
        ],
        correct_option_index=0,
        vocabulary_breakdown={
            "das Treffen": "la reunión / encuentro",
            "beginnt": "comienza (beginnen)",
            "Viertel": "cuarto de hora",
            "vor": "antes de (menos)",
        },
    ),
    Exercise(
        id="de-listen-a2-02",
        language="de-DE",
        category="Profesiones y Dativo (A2)",
        level="A2",
        skill_type="listening",
        title="¿En qué trabaja Maria?",
        prompt="👂 Escucha el audio y elige a qué se dedica Maria:",
        target_text="Maria arbeitet als Ärztin in einem großen Krankenhaus.",
        translation_es="Maria trabaja como médica en un hospital grande.",
        tip="Escucha la palabra compuesta 'Krankenhaus' y la profesión 'Ärztin'.",
        options=[
            "Es profesora en una universidad",
            "Es médica en un hospital",
            "Es abogada en una oficina",
        ],
        correct_option_index=1,
        vocabulary_breakdown={
            "arbeiten als": "trabajar como",
            "die Ärztin": "la médica",
            "das Krankenhaus": "el hospital",
            "groß": "grande",
        },
    ),
    Exercise(
        id="de-listen-a2-03",
        language="de-DE",
        category="Compras y Precios Compuestos (A2)",
        level="A2",
        skill_type="listening",
        title="¿Cuánto cuesta el diccionario?",
        prompt="👂 Escucha atentamente el precio exacto mencionado en el audio:",
        target_text="Das deutsche Wörterbuch kostet genau neunzehn Euro fünfzig.",
        translation_es="El diccionario de alemán cuesta exactamente 19,50 euros.",
        tip="Distingue entre 'neunzehn' (19) y 'neunzig' (90).",
        options=[
            "19,50 € (neunzehn Euro fünfzig)",
            "90,15 € (neunzig Euro fünfzehn)",
            "9,50 € (neun Euro fünfzig)",
        ],
        correct_option_index=0,
        vocabulary_breakdown={
            "das Wörterbuch": "el diccionario",
            "kostet": "cuesta",
            "neunzehn": "diecinueve (19)",
            "genau": "exactamente",
        },
    ),
    Exercise(
        id="de-listen-a2-04",
        language="de-DE",
        category="Transporte y Andenes (A2)",
        level="A2",
        skill_type="listening",
        title="Anuncio en la estación de trenes (Gleis)",
        prompt="👂 Escucha el aviso de la estación: ¿En qué vía sale el tren hacia Hamburgo?",
        target_text="Der Intercity nach Hamburg fährt heute von Gleis sieben ab.",
        translation_es="El Intercity hacia Hamburgo sale hoy desde la vía 7.",
        tip="Identifica la palabra clave 'Gleis' (vía / andén) seguida del número.",
        options=[
            "Vía 4 (Gleis vier)",
            "Vía 7 (Gleis sieben)",
            "Vía 11 (Gleis elf)",
        ],
        correct_option_index=1,
        vocabulary_breakdown={
            "das Gleis": "la vía / el andén",
            "fährt ab": "sale / parte (abfahren)",
            "heute": "hoy",
        },
    ),
    Exercise(
        id="de-listen-a2-05",
        language="de-DE",
        category="El Clima y Temperaturas (A2)",
        level="A2",
        skill_type="listening",
        title="Pronóstico meteorológico",
        prompt="👂 Escucha el informe del tiempo: ¿Cómo estará el clima mañana?",
        target_text="Morgen scheint die Sonne und es wird warm mit dreiundzwanzig Grad.",
        translation_es="Mañana brillará el sol y estará cálido con 23 grados.",
        tip="Escucha 'scheint die Sonne' (soleado) y el número 'dreiundzwanzig' (23).",
        options=[
            "Lluvioso y frío con 13 grados",
            "Soleado y cálido con 23 grados",
            "Nublado y ventoso con 30 grados",
        ],
        correct_option_index=1,
        vocabulary_breakdown={
            "die Sonne scheint": "el sol brilla",
            "warm": "cálido",
            "dreiundzwanzig": "veintitrés (23)",
            "der Grad": "el grado de temperatura",
        },
    ),
    Exercise(
        id="de-listen-a2-06",
        language="de-DE",
        category="Direcciones en la Ciudad (A2)",
        level="A2",
        skill_type="listening",
        title="¿Cómo llegar a la farmacia (Apotheke)?",
        prompt="👂 Escucha las indicaciones del transeúnte: ¿Qué debes hacer primero?",
        target_text="Gehen Sie an der Kreuzung geradeaus und biegen Sie nach der Post links ab.",
        translation_es="Siga todo recto en el cruce y gire a la izquierda después de la oficina postal.",
        tip="Identifica 'geradeaus' (recto), 'links' (izquierda) y el punto de referencia 'nach der Post'.",
        options=[
            "Girar a la derecha inmediatamente en el semáforo",
            "Ir todo recto en el cruce y girar a la izquierda tras la oficina postal",
            "Cruzar el parque y tomar el autobús",
        ],
        correct_option_index=1,
        vocabulary_breakdown={
            "die Kreuzung": "el cruce / intersección",
            "geradeaus": "recto / derecho",
            "links abbiegen": "girar a la izquierda",
            "die Post": "el correo / oficina postal",
        },
    ),
    Exercise(
        id="de-listen-a2-07",
        language="de-DE",
        category="Consulta Médica (A2)",
        level="A2",
        skill_type="listening",
        title="Instrucciones sobre medicamentos",
        prompt="👂 Escucha la recomendación del doctor: ¿Cómo se debe tomar el jarabe?",
        target_text="Nehmen Sie diesen Hustensaft dreimal täglich nach dem Essen ein.",
        translation_es="Tome este jarabe para la tos tres veces al día después de comer.",
        tip="Escucha 'dreimal täglich' (tres veces al día) y 'nach dem Essen' (después de comer).",
        options=[
            "Una vez al día antes de acostarse",
            "Tres veces al día después de las comidas",
            "Dos cucharadas cada hora",
        ],
        correct_option_index=1,
        vocabulary_breakdown={
            "der Hustensaft": "el jarabe para la tos",
            "dreimal täglich": "tres veces al día",
            "nach dem Essen": "después de comer",
            "einnehmen": "tomar medicamento",
        },
    ),
    Exercise(
        id="de-listen-a2-08",
        language="de-DE",
        category="En el Restaurante (A2)",
        level="A2",
        skill_type="listening",
        title="Pago de la cuenta (Zahlen)",
        prompt="👂 Escucha al cliente: ¿Qué método de pago solicita?",
        target_text="Wir möchten bitte getrennt und mit Kreditkarte zahlen.",
        translation_es="Nos gustaría pagar por separado y con tarjeta de crédito, por favor.",
        tip="'getrennt' significa cuentas separadas (muy común en Alemania).",
        options=[
            "Pagar juntos y en efectivo",
            "Pagar por separado y con tarjeta de crédito",
            "Pedir el postre primero",
        ],
        correct_option_index=1,
        vocabulary_breakdown={
            "getrennt": "por separado",
            "die Kreditkarte": "la tarjeta de crédito",
            "zahlen": "pagar",
        },
    ),
    Exercise(
        id="de-listen-a2-09",
        language="de-DE",
        category="Buzón de Voz (A2)",
        level="A2",
        skill_type="listening",
        title="Mensaje en el contestador automático",
        prompt="👂 Escucha el mensaje de voz: ¿Para qué llama Herr Schmidt?",
        target_text="Hallo, hier ist Herr Schmidt. Ich muss unseren Termin am Donnerstag leider verschieben.",
        translation_es="Hola, habla el señor Schmidt. Lamentablemente debo posponer nuestra cita del jueves.",
        tip="'verschieben' significa aplazar o posponer una cita fijada.",
        options=[
            "Para confirmar la llegada a la cita puntual",
            "Para posponer la cita fijada para el jueves",
            "Para cancelar el contrato definitivamente",
        ],
        correct_option_index=1,
        vocabulary_breakdown={
            "verschieben": "posponer / aplazar",
            "der Termin": "la cita",
            "leider": "lamentablemente",
        },
    ),

    # --- B1 (Independencia: Negocios, tecnología, noticias) ---
    Exercise(
        id="de-listen-b1-01",
        language="de-DE",
        category="Entrevista Laboral (Hören B1)",
        level="B1",
        skill_type="listening",
        title="Requisitos del puesto laboral",
        prompt="👂 Escucha al entrevistador: ¿Cuál es el requisito indispensable para el puesto?",
        target_text="Für diese Position setzen wir verhandlungssichere Deutschkenntnisse in Wort und Schrift voraus.",
        translation_es="Para este puesto exigimos conocimientos de alemán a nivel de negociación, tanto oral como escrito.",
        tip="'verhandlungssicher' denota nivel fluido/profesional (B2-C1). 'voraussetzen' significa requerir de antemano.",
        options=[
            "Disponibilidad de viajar los fines de semana",
            "Alemán fluido profesional hablado y escrito",
            "Tener vehículo propio",
        ],
        correct_option_index=1,
        vocabulary_breakdown={
            "voraussetzen": "exigir como requisito",
            "verhandlungssicher": "con nivel de negociación / plenamente fluido",
            "in Wort und Schrift": "hablado y escrito",
        },
    ),
    Exercise(
        id="de-listen-b1-02",
        language="de-DE",
        category="Noticias y Tráfico (Hören B1)",
        level="B1",
        skill_type="listening",
        title="Reporte de tráfico en la autopista (Autobahn)",
        prompt="👂 Escucha el boletín de tráfico: ¿Cuál es el motivo del atasco en la A8?",
        target_text="Auf der Autobahn A8 gibt es wegen einer Baustelle zehn Kilometer Stau.",
        translation_es="En la autopista A8 hay un atasco de diez kilómetros debido a obras en la calzada.",
        tip="'der Stau' es atasco/tráfico. 'die Baustelle' son obras de construcción.",
        options=[
            "Un accidente grave entre dos camiones",
            "Un atasco de 10 km ocasionado por obras viales",
            "Cierre por tormenta de nieve intensa",
        ],
        correct_option_index=1,
        vocabulary_breakdown={
            "der Stau": "el atasco / embotellamiento vehicular",
            "die Baustelle": "las obras de construcción",
            "wegen": "a causa de / debido a",
        },
    ),
    # =========================================================================
    # INGLÉS - ESCRITURA (Writing) A1, A2, B1
    # =========================================================================
    Exercise(
        id="en-write-01",
        language="en-US",
        category="Present Simple y Rutinas",
        level="A1",
        skill_type="writing",
        title="Tercera Persona en Presente",
        prompt="✍️ Escribe en inglés: 'Ella trabaja en un banco y vive cerca de aquí.'",
        target_text="She works in a bank and lives near here.",
        translation_es="Ella trabaja en un banco y vive cerca de aquí.",
        tip="En presente simple con he/she/it, no olvides añadir la '-s' final a los verbos: 'works' y 'lives'.",
        vocabulary_breakdown={
            "works": "trabaja (work + s)",
            "lives": "vive (live + s)",
            "bank": "banco",
            "near here": "cerca de aquí",
        },
        grammar_note="La tercera persona del singular en inglés requiere -s o -es en oraciones afirmativas.",
    ),
    Exercise(
        id="en-write-02",
        language="en-US",
        category="Present Continuous",
        level="A1",
        skill_type="writing",
        title="Acciones en progreso en este momento",
        prompt="✍️ Traduce al inglés: 'Ellos están estudiando en la biblioteca ahora mismo.'",
        target_text="They are studying in the library right now.",
        translation_es="Ellos están estudiando en la biblioteca ahora mismo.",
        tip="Estructura: Sujeto + verbo to be (are) + verbo con terminación -ing (studying).",
        vocabulary_breakdown={
            "they are": "ellos son / están",
            "studying": "estudiando (study + ing)",
            "library": "biblioteca (no confundir con librería/bookstore)",
            "right now": "ahora mismo",
        },
        grammar_note="Usa el Present Continuous para acciones que se desarrollan en el momento exacto del habla.",
    ),
    Exercise(
        id="en-write-03",
        language="en-US",
        category="Preguntas con Do / Does",
        level="A1",
        skill_type="writing",
        title="Preguntas en presente simple",
        prompt="✍️ Formula la pregunta en inglés: '¿Vives en una casa grande con tu familia?'",
        target_text="Do you live in a big house with your family?",
        translation_es="¿Vives en una casa grande con tu familia?",
        tip="Inicia preguntas en presente simple con el auxiliar 'Do' cuando el sujeto es 'you'.",
        vocabulary_breakdown={
            "do": "auxiliar interrogativo (sin traducción literal)",
            "live": "vivir",
            "big house": "casa grande (el adjetivo va antes del sustantivo)",
            "your family": "tu familia",
        },
        grammar_note="En inglés los adjetivos calificativos siempre van antes del sustantivo: 'big house', nunca 'house big'.",
    ),
    Exercise(
        id="en-write-04",
        language="en-US",
        category="There is / There are",
        level="A1",
        skill_type="writing",
        title="Existencia de objetos",
        prompt="✍️ Escribe en inglés: 'Hay tres manzanas rojas sobre la mesa.'",
        target_text="There are three red apples on the table.",
        translation_es="Hay tres manzanas rojas sobre la mesa.",
        tip="Usa 'There are' para plural y 'There is' para singular.",
        vocabulary_breakdown={
            "there are": "hay (plural)",
            "red apples": "manzanas rojas",
            "on the table": "sobre la mesa",
        },
        grammar_note="'There is' se utiliza para nombres contables en singular o incontables; 'There are' para plural.",
    ),
    Exercise(
        id="en-write-05",
        language="en-US",
        category="Adverbios de Frecuencia",
        level="A1",
        skill_type="writing",
        title="Posición de 'always', 'usually', 'never'",
        prompt="✍️ Traduce al inglés: 'Siempre tomo café por la mañana antes de ir a trabajar.'",
        target_text="I always drink coffee in the morning before going to work.",
        translation_es="Siempre tomo café por la mañana antes de ir a trabajar.",
        tip="El adverbio 'always' se ubica entre el sujeto y el verbo principal.",
        vocabulary_breakdown={
            "always": "siempre",
            "drink coffee": "beber/tomar café",
            "in the morning": "por la mañana",
            "before going": "antes de ir (después de preposición va verbo con -ing)",
        },
        grammar_note="Tras preposiciones como 'before' o 'after', los verbos van en gerundio (-ing): 'before going'.",
    ),
    Exercise(
        id="en-write-06",
        language="en-US",
        category="Past Simple Irregular",
        level="A2",
        skill_type="writing",
        title="Objetos Perdidos en Pasado",
        prompt="✍️ Traduce al inglés en pasado simple: 'Ayer encontré mis llaves debajo de la cama.'",
        target_text="Yesterday I found my keys under the bed.",
        translation_es="Ayer encontré mis llaves debajo de la cama.",
        tip="'find' es un verbo irregular: su pasado simple es 'found', no 'finded'.",
        vocabulary_breakdown={
            "found": "encontré (pasado de find)",
            "keys": "llaves",
            "under": "debajo de",
            "bed": "cama",
        },
        grammar_note="Los verbos irregulares en inglés cambian su raíz en pasado simple.",
    ),
    Exercise(
        id="en-write-07",
        language="en-US",
        category="Comparativos y Superlativos",
        level="A2",
        skill_type="writing",
        title="Comparar transportes",
        prompt="✍️ Traduce: 'El tren es mucho más rápido y cómodo que el autobús.'",
        target_text="The train is much faster and more comfortable than the bus.",
        translation_es="El tren es mucho más rápido y cómodo que el autobús.",
        tip="Adjetivo corto: fast ➔ faster. Adjetivo largo: comfortable ➔ more comfortable.",
        vocabulary_breakdown={
            "faster": "más rápido (fast + er)",
            "more comfortable": "más cómodo",
            "than": "que (en comparaciones)",
        },
        grammar_note="Los adjetivos de una sílaba añaden '-er than'; los de tres o más sílabas usan 'more [adjetivo] than'.",
    ),
    Exercise(
        id="en-write-08",
        language="en-US",
        category="Futuro con 'going to'",
        level="A2",
        skill_type="writing",
        title="Planes e intenciones futuras",
        prompt="✍️ Escribe con 'going to': 'Vamos a comprar un nuevo departamento el próximo mes.'",
        target_text="We are going to buy a new apartment next month.",
        translation_es="Vamos a comprar un nuevo apartamento el próximo mes.",
        tip="Usa 'are going to' + verbo base ('buy'). 'Next month' no lleva preposición.",
        vocabulary_breakdown={
            "are going to": "vamos a (intención planificada)",
            "buy": "comprar",
            "apartment": "apartamento / piso",
            "next month": "el próximo mes",
        },
        grammar_note="'be going to' se prefiere sobre 'will' para planes o decisiones tomadas con anterioridad.",
    ),
    Exercise(
        id="en-write-09",
        language="en-US",
        category="Primer Condicional (First Conditional)",
        level="A2",
        skill_type="writing",
        title="Causa y efecto en el futuro",
        prompt="✍️ Escribe en inglés: 'Si llueve mañana, nos quedaremos en casa y veremos una película.'",
        target_text="If it rains tomorrow, we will stay at home and watch a movie.",
        translation_es="Si llueve mañana, nos quedaremos en casa y veremos una película.",
        tip="En la cláusula con 'if' se usa presente simple ('rains'); en el resultado se usa 'will' + infinitivo.",
        vocabulary_breakdown={
            "if it rains": "si llueve (3ra persona con -s)",
            "we will stay": "nos quedaremos",
            "at home": "en casa",
            "watch a movie": "ver una película",
        },
        grammar_note="Estructura First Conditional: If + Present Simple, will + base form.",
    ),
    Exercise(
        id="en-write-10",
        language="en-US",
        category="Modales de Obligación (Must / Have to)",
        level="A2",
        skill_type="writing",
        title="Normas y reglamentos",
        prompt="✍️ Escribe en inglés: 'Tienes que mostrar tu pasaporte en el mostrador del aeropuerto.'",
        target_text="You have to show your passport at the airport desk.",
        translation_es="Tienes que mostrar tu pasaporte en el mostrador del aeropuerto.",
        tip="Usa 'have to' para obligaciones externas o requisitos formales.",
        vocabulary_breakdown={
            "have to": "tener que (obligación)",
            "show": "mostrar / enseñar",
            "passport": "pasaporte",
            "desk": "mostrador / escritorio",
        },
        grammar_note="'have to' expresa reglas o leyes impuestas por terceros; 'must' a menudo expresa convicción personal.",
    ),
    Exercise(
        id="en-write-11",
        language="en-US",
        category="Present Perfect vs Past Simple",
        level="B1",
        skill_type="writing",
        title="Experiencia y Duración en el Tiempo",
        prompt="✍️ Traduce usando Present Perfect: 'He vivido en esta ciudad durante tres años.'",
        target_text="I have lived in this city for three years.",
        translation_es="He vivido en esta ciudad durante tres años.",
        tip="Usa 'for' para indicar duración ('for three years') y 'since' para un punto de inicio específico.",
        vocabulary_breakdown={
            "have lived": "he vivido (present perfect)",
            "for": "durante (periodo de tiempo acumulado)",
            "since": "desde (año o fecha específica)",
            "city": "ciudad",
        },
        grammar_note="El Present Perfect conecta una acción que empezó en el pasado y continúa en el presente.",
    ),
    Exercise(
        id="en-write-12",
        language="en-US",
        category="Segundo Condicional (Second Conditional)",
        level="B1",
        skill_type="writing",
        title="Situaciones hipotéticas e imaginarias",
        prompt="✍️ Traduce con 2nd conditional: 'Si tuviera un millón de dólares, viajaría por todo el mundo.'",
        target_text="If I had a million dollars, I would travel around the world.",
        translation_es="Si tuviera un millón de dólares, viajaría por todo el mundo.",
        tip="Estructura: If + Past Simple ('had'), would + verbo base ('travel').",
        vocabulary_breakdown={
            "had": "tuviera / tuviese (pasado de have)",
            "million dollars": "millón de dólares",
            "would travel": "viajaría",
            "around the world": "por todo el mundo",
        },
        grammar_note="El Second Conditional se usa para situaciones irreales, hipotéticas o sueños en el presente.",
    ),
    Exercise(
        id="en-write-13",
        language="en-US",
        category="Voz Pasiva Formal (Passive Voice)",
        level="B1",
        skill_type="writing",
        title="Informes empresariales y procesos",
        prompt="✍️ Traduce en pasiva formal: 'El informe final fue enviado por el gerente de proyectos ayer.'",
        target_text="The final report was sent by the project manager yesterday.",
        translation_es="El informe final fue enviado por el director de proyectos ayer.",
        tip="Pasiva en pasado simple: was/were + participio ('sent') + by [agente].",
        vocabulary_breakdown={
            "final report": "informe final",
            "was sent": "fue enviado (send ➔ sent)",
            "project manager": "jefe / gerente de proyectos",
        },
        grammar_note="La voz pasiva se usa cuando el objeto de la acción es más relevante que la persona que la realiza.",
    ),
    Exercise(
        id="en-write-14",
        language="en-US",
        category="Estilo Indirecto (Reported Speech)",
        level="B1",
        skill_type="writing",
        title="Transmitir lo dicho por otra persona",
        prompt="✍️ Escribe en reported speech: 'Ella me dijo que ya había terminado la presentación.'",
        target_text="She told me that she had already finished the presentation.",
        translation_es="Ella me dijo que ya había terminado la presentación.",
        tip="En reported speech, el pasado o present perfect retrocede un tiempo a Past Perfect ('had finished').",
        vocabulary_breakdown={
            "told me": "me dijo (tell + pronombre objeto)",
            "had already finished": "ya había terminado (Past Perfect)",
            "presentation": "presentación",
        },
        grammar_note="Al pasar a estilo indirecto con un verbo introductorio en pasado ('told'), los tiempos verbales retroceden (backshift).",
    ),
    # =========================================================================
    # INGLÉS - COMPRENSIÓN AUDITIVA (Listening) - Cambridge A1 Key & Oxford 3000
    # =========================================================================

    # --- A1 (Supervivencia: Frases directas, números básicos, bebidas y lugares diarios) ---
    Exercise(
        id="en-listen-a1-01",
        language="en-US",
        category="Cafetería y Pedidos (A1)",
        level="A1",
        skill_type="listening",
        title="Ordenando bebidas en una cafetería",
        prompt="👂 Escucha el pedido: ¿Qué bebidas pidió la persona?",
        target_text="Can I have an orange juice and a bottle of water, please?",
        translation_es="¿Me da un jugo de naranja y una botella de agua, por favor?",
        tip="Identifica las dos bebidas básicas: 'orange juice' y 'water'.",
        options=[
            "Jugo de naranja y una botella de agua",
            "Jugo de manzana y un café caliente",
            "Té con leche y una galleta",
        ],
        correct_option_index=0,
        vocabulary_breakdown={
            "orange juice": "jugo / zumo de naranja",
            "bottle of water": "botella de agua",
            "please": "por favor",
        },
    ),
    Exercise(
        id="en-listen-a1-02",
        language="en-US",
        category="Presentación y Origen (A1)",
        level="A1",
        skill_type="listening",
        title="¿De dónde es David?",
        prompt="👂 Escucha con atención: ¿De qué país es David?",
        target_text="Hello, my name is David and I am from Mexico.",
        translation_es="Hola, mi nombre es David y soy de México.",
        tip="Escucha la frase de origen: 'from Mexico'.",
        options=[
            "De México (from Mexico)",
            "De Canadá (from Canada)",
            "De España (from Spain)",
        ],
        correct_option_index=0,
        vocabulary_breakdown={
            "my name is": "mi nombre es",
            "I am from": "soy de / vengo de",
            "Mexico": "México",
        },
    ),
    Exercise(
        id="en-listen-a1-03",
        language="en-US",
        category="Compras y Precios Básicos (A1)",
        level="A1",
        skill_type="listening",
        title="Precio de un sándwich",
        prompt="👂 Escucha el precio: ¿Cuánto cuesta el sándwich?",
        target_text="The chicken sandwich is four dollars.",
        translation_es="El sándwich de pollo cuesta cuatro dólares.",
        tip="Concéntrate en el número básico 'four' (4) antes de 'dollars'.",
        options=[
            "$4 dólares (four dollars)",
            "$14 dólares (fourteen dollars)",
            "$40 dólares (forty dollars)",
        ],
        correct_option_index=0,
        vocabulary_breakdown={
            "chicken sandwich": "sándwich de pollo",
            "four dollars": "cuatro dólares ($4)",
        },
    ),
    Exercise(
        id="en-listen-a1-04",
        language="en-US",
        category="Horas y Citas Simples (A1)",
        level="A1",
        skill_type="listening",
        title="¿A qué hora empieza la película?",
        prompt="👂 Escucha la hora indicada: ¿Cuándo empieza la función?",
        target_text="The movie starts at seven o'clock.",
        translation_es="La película empieza a las siete en punto.",
        tip="En nivel A1 las horas exactas usan 'at [número] o'clock'.",
        options=[
            "A las 5:00 (five o'clock)",
            "A las 7:00 (seven o'clock)",
            "A las 9:00 (nine o'clock)",
        ],
        correct_option_index=1,
        vocabulary_breakdown={
            "movie": "película",
            "starts": "empieza / comienza",
            "seven o'clock": "siete en punto",
        },
    ),
    Exercise(
        id="en-listen-a1-05",
        language="en-US",
        category="Días de la Semana (A1)",
        level="A1",
        skill_type="listening",
        title="¿Qué día abre el museo?",
        prompt="👂 Escucha el día mencionado: ¿Cuándo está abierto el museo?",
        target_text="The art museum is open on Saturday.",
        translation_es="El museo de arte está abierto el sábado.",
        tip="Los días de la semana en inglés se acompañan de la preposición 'on'.",
        options=[
            "El martes (on Tuesday)",
            "El jueves (on Thursday)",
            "El sábado (on Saturday)",
        ],
        correct_option_index=2,
        vocabulary_breakdown={
            "art museum": "museo de arte",
            "open": "abierto",
            "on Saturday": "el sábado",
        },
    ),

    # --- A2 (Plataforma: Aeropuertos, hoteles, médicos, cancelaciones) ---
    Exercise(
        id="en-listen-a2-01",
        language="en-US",
        category="Avisos en el Aeropuerto (A2)",
        level="A2",
        skill_type="listening",
        title="Cancelación de vuelo",
        prompt="👂 Escucha el anuncio de voz y responde: ¿Por qué se canceló el vuelo?",
        target_text="Attention passengers, flight 402 is cancelled due to heavy rain.",
        translation_es="Atención pasajeros, el vuelo 402 está cancelado debido a lluvia intensa.",
        tip="Identifica la expresión 'due to' (debido a) y la condición climática.",
        options=[
            "Por lluvia intensa (heavy rain)",
            "Por fallas mecánicas en el avión",
            "Por huelga del personal del aeropuerto",
        ],
        correct_option_index=0,
        vocabulary_breakdown={
            "due to": "debido a / a causa de",
            "cancelled": "cancelado",
            "heavy rain": "lluvia intensa",
            "flight": "vuelo",
        },
    ),
    Exercise(
        id="en-listen-a2-02",
        language="en-US",
        category="Cafetería y Opciones Dietéticas (A2)",
        level="A2",
        skill_type="listening",
        title="Café helado y tipo de leche",
        prompt="👂 Escucha el pedido: ¿Qué tipo de leche pidió el cliente?",
        target_text="I would like a large iced coffee with almond milk and no sugar, please.",
        translation_es="Quisiera un café helado grande con leche de almendras y sin azúcar, por favor.",
        tip="Escucha la palabra clave sobre la leche: 'almond milk'.",
        options=[
            "Leche de vaca entera",
            "Leche de avena (oat milk)",
            "Leche de almendras (almond milk)",
        ],
        correct_option_index=2,
        vocabulary_breakdown={
            "iced coffee": "café helado",
            "almond milk": "leche de almendras",
            "no sugar": "sin azúcar",
        },
    ),
    Exercise(
        id="en-listen-a2-03",
        language="en-US",
        category="Recepción de Hotel y Horarios (A2)",
        level="A2",
        skill_type="listening",
        title="Horario del desayuno en el hotel",
        prompt="👂 Escucha al recepcionista: ¿A qué hora termina el desayuno?",
        target_text="Good morning! Breakfast is served in the main dining room from seven until ten thirty.",
        translation_es="¡Buenos días! El desayuno se sirve en el comedor principal de 7:00 a 10:30.",
        tip="'until ten thirty' indica el límite de horario.",
        options=[
            "A las 9:00",
            "A las 10:00",
            "A las 10:30 (ten thirty)",
        ],
        correct_option_index=2,
        vocabulary_breakdown={
            "served": "servido",
            "dining room": "comedor",
            "until": "hasta",
            "ten thirty": "diez y media (10:30)",
        },
    ),
    Exercise(
        id="en-listen-a2-04",
        language="en-US",
        category="Salud y Farmacia (A2)",
        level="A2",
        skill_type="listening",
        title="Instrucciones médicas para pastillas",
        prompt="👂 Escucha al farmacéutico: ¿Cuándo debes tomar estas pastillas?",
        target_text="Take one pill every eight hours with a full glass of water after meals.",
        translation_es="Toma una pastilla cada ocho horas con un vaso lleno de agua después de las comidas.",
        tip="Escucha el intervalo de tiempo: 'every eight hours'.",
        options=[
            "Cada 8 horas después de las comidas",
            "Cada 12 horas en ayunas",
            "Únicamente antes de dormir",
        ],
        correct_option_index=0,
        vocabulary_breakdown={
            "pill": "pastilla / píldora",
            "every eight hours": "cada ocho horas",
            "full glass": "vaso lleno",
            "after meals": "después de comer",
        },
    ),
    Exercise(
        id="en-listen-a2-05",
        language="en-US",
        category="Transporte y Trenes (A2)",
        level="A2",
        skill_type="listening",
        title="Retraso del tren a Chicago",
        prompt="👂 Escucha el aviso de la estación: ¿De cuántos minutos es el retraso?",
        target_text="The train bound for Chicago has been delayed by twenty-five minutes due to maintenance work.",
        translation_es="El tren con destino a Chicago ha sido demorado veinticinco minutos debido a tareas de mantenimiento.",
        tip="'twenty-five minutes' indica el tiempo exacto de demora.",
        options=[
            "15 minutos",
            "25 minutos",
            "45 minutos",
        ],
        correct_option_index=1,
        vocabulary_breakdown={
            "bound for": "con destino a",
            "delayed": "demorado / retrasado",
            "maintenance work": "trabajos de mantenimiento",
        },
    ),
    Exercise(
        id="en-listen-a2-06",
        language="en-US",
        category="Atención al Cliente (A2)",
        level="A2",
        skill_type="listening",
        title="Política de devoluciones de la tienda",
        prompt="👂 Escucha a la representante de servicio al cliente: ¿Qué necesitas para el reembolso completo?",
        target_text="You can return any purchased item within thirty days as long as you have the original receipt.",
        translation_es="Puedes devolver cualquier artículo comprado dentro de los 30 días siempre que tengas el recibo original.",
        tip="'as long as' significa 'siempre que' o 'a condición de'. 'receipt' es el recibo.",
        options=[
            "La etiqueta de garantía de fábrica",
            "El recibo original de compra (original receipt)",
            "Pagar una tarifa de reposición",
        ],
        correct_option_index=1,
        vocabulary_breakdown={
            "return": "devolver",
            "within thirty days": "dentro de 30 días",
            "as long as": "siempre que / con tal de que",
            "original receipt": "recibo / comprobante original",
        },
    ),

    # --- B1 (Independencia: Negocios, tecnología, noticias) ---
    Exercise(
        id="en-listen-b1-01",
        language="en-US",
        category="Reuniones de Negocios (Hören B1)",
        level="B1",
        skill_type="listening",
        title="Cambio de fecha límite del proyecto",
        prompt="👂 Escucha al gerente en la videollamada: ¿Para cuándo se postergó la fecha límite?",
        target_text="Because the client requested additional features, we have moved the final launch deadline to next Friday.",
        translation_es="Dado que el cliente solicitó funciones adicionales, hemos trasladado la fecha límite de lanzamiento final al próximo viernes.",
        tip="Presta atención a la nueva fecha: 'next Friday' (el próximo viernes).",
        options=[
            "Se canceló el proyecto",
            "Se mantuvo para este miércoles",
            "Se postergó al próximo viernes (next Friday)",
        ],
        correct_option_index=2,
        vocabulary_breakdown={
            "requested": "solicitó",
            "additional features": "funciones adicionales",
            "deadline": "fecha límite",
            "moved to": "trasladado / reprogramado para",
        },
    ),
    Exercise(
        id="en-listen-b1-02",
        language="en-US",
        category="Innovación y Tecnología (Hören B1)",
        level="B1",
        skill_type="listening",
        title="Actualización de software y batería",
        prompt="👂 Escucha el podcast de tecnología: ¿Cuál es el principal beneficio de la nueva versión?",
        target_text="The latest system update optimizes background processing and extends total battery life by twenty percent.",
        translation_es="La última actualización del sistema optimiza el procesamiento en segundo plano y prolonga la duración total de la batería en un 20%.",
        tip="Identifica el beneficio específico: extender la vida útil de la batería en un 20%.",
        options=[
            "Aumenta la memoria RAM en 50%",
            "Extiende la duración de la batería un 20%",
            "Reduce el tamaño de la pantalla",
        ],
        correct_option_index=1,
        vocabulary_breakdown={
            "latest update": "última actualización",
            "optimizes": "optimiza",
            "extends": "extiende / prolonga",
            "battery life": "duración de la batería",
        },
    ),
]


def get_exercises(
    language: Optional[str] = None,
    category: Optional[str] = None,
    level: Optional[str] = None,
    skill_type: Optional[str] = None,
) -> List[Exercise]:
    results = EXERCISES_DATABASE
    if language:
        results = [e for e in results if e.language.lower() == language.lower()]
    if category:
        results = [e for e in results if e.category.lower() == category.lower()]
    if level:
        results = [e for e in results if e.level.lower() == level.lower()]
    if skill_type:
        target_skill = (
            "listening"
            if skill_type.lower() in ("listening", "comprehension")
            else skill_type.lower()
        )
        results = [e for e in results if (e.skill_type or "speaking").lower() == target_skill]
    return results


def get_categories(language: str) -> List[str]:
    seen = set()
    categories = []
    for e in EXERCISES_DATABASE:
        if e.language.lower() == language.lower() and e.category not in seen:
            seen.add(e.category)
            categories.append(e.category)
    return categories
